### ISSUE TITLE
Question: Is there a way to navigate the table with key arrows?

### ISSUE THREAD

**Issue by barucAlmaguer** [komarovalexander/ka-table#111]
Hi, great project! looking forward to use it and give feedback about it 😄 

I was looking at the demos (specially, the "focus" one) and it works fine, I just have this question.

The keyboard navigation in that demo seems very simple (iterate on each tab press, each row cell, then jump to next row).

Is there a way to turn it to a excel/google sheets navigation?
In this case, you could move around the table with the arrow keys, with Enter key go to edit mode and so on (maybe even navigate to last row/column with ctrl+arrows or move between pages if paging enabled somehow).

what could be the best approach to achieve this?
is feasible in the current state of the library or new features should be implemented in order to make it possible?

**Comment by komarovalexander** [comment]
Hi
Thanks for the question - It is a great proposal. I was thinking to add a demo with described behavior but decided to make the simplest one first and wait for feedback from users. 

I wanted to provide you an example on stackblitz but it does not work properly this time 
https://github.com/stackblitz/core/issues/1367 - I hope they will fix it soon.

The main idea of the ka-table is that it should be extendable, therefore to show you how to achieve it, I've quickly created a demo 
https://komarovalexander.github.io/ka-table/#/keyboard-navigation
you can use it now as a basis to make any keyboard navigation you want

P.S. again thanks for your ideas, I will keep this issue open for a couple of weeks. I will investigate it better and probably will add helpers methods to make it with less code.

if you have any proposals feel free to provide them here

**Comment by barucAlmaguer** [comment]
That's great!
yes, it works perfectly as a basis for keyboard navigation, thanks

I see what you mean, the current code needed for the keyboard navigation is rather verbose but otherwise works great.
a helper function to quickly add keyboard navigation would be awesome.

I will continue to use the table and drop further questions / suggestions in the issues page 👍🏼

**Comment by komarovalexander** [comment]
Hi @barucAlmaguer 
I've just released  6.4.0
It has some useful features for implementing keyboard navigation.
Check them out here: https://komarovalexander.github.io/ka-table/#/keyboard-navigation
Release page: https://github.com/komarovalexander/ka-table/releases/tag/6.4.0
