### ISSUE TITLE
Multiple Selection does not work for any "rowKeyField" value other than "id"

### ISSUE THREAD

**Issue by Hkataya** [komarovalexander/ka-table#114]
Hey, awesome project! really covers almost all use cases for a datatable.

I was checking the multiple selection demo ( https://stackblitz.com/edit/table-selection-js?file=Demo.js ) and it works well as long as rowKeyFiled : "id", once you change the value of the rowKeyField and update it in the data array, the selection stops working properly. 

This is what I'm trying to achieve ( https://stackblitz.com/edit/table-selection-js-lty3ay?file=Demo.js )

Not sure if this is a bug or I'm missing something.

Thanks again for the awesome library!

**Comment by komarovalexander** [comment]
Hi @Hkataya 
Do you mean the header checkbox does not work properly in the provided example? or there are other cases as well?
![image](https://user-images.githubusercontent.com/17903747/105705716-da35b380-5f10-11eb-8297-2a73eab2ba9f.png)

I will try to fix it today evening and will notify you when a new minor version will be published.
thanks for the feedback!

**Comment by komarovalexander** [comment]
Fixed https://stackblitz.com/edit/table-selection-js-czrbhu?file=Demo.js starting from `6.4.3` version
