### ISSUE TITLE
Add dynamic page size selection

### ISSUE THREAD

**Issue by alphabetek** [komarovalexander/ka-table#120]
Thanks for the great job to make this library available! It is loaded with awesome features, I think it would be really nice to have select input (like all paginated tables offer) to configure the number of rows per page. Looking at documentation and examples I don't see such option.

**Comment by komarovalexander** [comment]
Hi @alphabetek , thanks for this request! I was considering adding it, but just was waiting for real requests from users. It is definitely worth to be implemented. I will add these settings soon (approx. in 2 day - 1 week)

**Comment by komarovalexander** [comment]
6.6.0 has been released with this feature
Demo: https://komarovalexander.github.io/ka-table/#/paging
also, I've added a custom paging demo: https://komarovalexander.github.io/ka-table/#/custom-paging - can be useful as well 

Cheers!

**Comment by alphabetek** [comment]
Thanks @komarovalexander for the quick implementation! 🚀 👏
