### ISSUE TITLE
Allow style customization for tbody element

### ISSUE THREAD

**Issue by alphabetek** [komarovalexander/ka-table#121]
The promise of ka-table is to be able to customize every table html element, currently styles of tbody element are hard coded to use the default options.

**Comment by alphabetek** [comment]
Fix proposal: https://github.com/komarovalexander/ka-table/pull/122

**Comment by komarovalexander** [comment]
this is great!

**Comment by komarovalexander** [comment]
6.5.2 version was published with this fix
Demo https://stackblitz.com/edit/table-overview-ts-jgng8w?file=Demo.tsx
