### ISSUE TITLE
Minimal width for resizable columns

### ISSUE THREAD

**Issue by DmytroOSDB** [komarovalexander/ka-table#124]
Hello @komarovalexander :wave:

It would be great if you could add `minimal width` property for resizable columns which would specify width between two ends of a column despite what is inside
In my opinion, it could be even a config object to left some space for future developing like a
```
type Resizable =
  | {
      enabled: boolean;
      minWidth: number;
      maxWidth: number;
    }
  | boolean;
``` 

Thank you!

**Comment by komarovalexander** [comment]
Hi @DmytroOSDB ,
how do you feel about `column.style.minWidth` & `column.style.maxWidth` properties https://stackblitz.com/edit/table-column-resizing-ts-dzzwt1?file=Demo.tsx ?  
I already have support for minWidth in case of the resizable column, just need to add maxWidth support as well. 
I think I will be able to add maxWidth support this weekend.
Thanks for being active!

**Comment by DmytroOSDB** [comment]
Hi @komarovalexander 
Thank you for the quick answer! Yes, it works for me :ok_hand: Could I ask you to add it to the main demo to highlight it for others?

I proposed `maxWidth` due to it related to `width` in general and its implementation should be pretty similar with `minWidth`

**Comment by komarovalexander** [comment]
Hi @DmytroOSDB, I will add this case to the demo, thanks!
for `maxWidth` I will wait for a real use case and will add it later if required
