### ISSUE TITLE
Provide more control on paging component

### ISSUE THREAD

**Issue by alphabetek** [komarovalexander/ka-table#125]
Hello @komarovalexander, this is a question/request for enhancement, here is the scenario I would like to achieve:

- Be able to scroll the table only with fixed footer (`Paging` component), which makes sense when the user has a large table with `Paging` activated, he shouldn't navigate till the bottom in order to change the page;
I have tried to hack around CSS of different native table elements but couldn't achieve this. Do you have an idea if it is feasible?

As enhancement, I am thinking why not giving the possibility to put `Paging` component wherever we want (for example in the top rather than the footer).

This could be achieved if `Paging` component is extracted and not tightly coupled to `Table` component.

Thanks in advance!

**Comment by komarovalexander** [comment]
Hi @alphabetek 
> Be able to scroll the table only with fixed footer (Paging component),

`.ka-table-wrapper` styles should help you with it
```
.ka-table-wrapper {
  max-height: 400px;
}
```
demo:  https://stackblitz.com/edit/table-paging-ts-jj5w1t?file=style.scss

as for 

> This could be achieved if Paging component is extracted and not tightly coupled to Table component.

I think it should be done by overriding rootDiv structure https://stackblitz.com/edit/table-paging-ts-tivken?file=Demo.tsx , but paging should not be shown in the provided example - I will fix it as a bug soon

**Comment by komarovalexander** [comment]
But maybe something like paging.position would be easier solution for second case

**Comment by komarovalexander** [comment]
6.6.1 : https://stackblitz.com/edit/table-paging-ts-dcrdyb?file=style.scss

**Comment by komarovalexander** [comment]
HI @alphabetek
Starting from 6.7.0 you can use `paging.position` property 
demo: https://komarovalexander.github.io/ka-table/#/paging
