### ISSUE TITLE
How to add normal react button to each row

### ISSUE THREAD

**Issue by ianrae** [komarovalexander/ka-table#128]
I would like to implement my own edit feature where each row would have a react-bootstrap button which, when clicked, would launch a modal dialog box that I implement.

Do I use events to do this?  How to I add a column of react buttons?

Thanks, and ka-table is fantastic. Thanks for creating it.

**Comment by komarovalexander** [comment]
Hi @ianrae 
Please check out this demo https://komarovalexander.github.io/ka-table/#/alert-cell it has custom column with image button and it shows alert dialog by click. 
instead of image you can use bootstrap button, and modal dialog instead of alert.
Let me know if you need more info

**Comment by ianrae** [comment]
Perfect. Thanks!
