### ISSUE TITLE
While adding row with custom editor, updateCell creates row below.

### ISSUE THREAD

**Issue by AlexK0210** [komarovalexander/ka-table#130]
There is a bug, when using Custom Editor for some inputs
While adding new row, when value in custom editor saved it proceed new row with values of custom editor.

**Comment by komarovalexander** [comment]
Hi @AlexK0210 
May I ask you to fork and reproduce the issue on 
ts https://stackblitz.com/edit/table-add-row-ts-geh46e?file=Demo.tsx 
**or** 
js https://stackblitz.com/edit/table-add-row-js-gfpwvc?file=Demo.js
example

**Comment by AlexK0210** [comment]
@komarovalexander yep, will do it a while

**Comment by komarovalexander** [comment]
Hi @AlexK0210
You have to use `updateEditorValue` and it will work fine:
https://stackblitz.com/edit/table-add-row-ts-yprynw?file=Demo.tsx
Thanks for the question again!

**Comment by KarthikHebbarMN** [comment]
Hey, I'm stuck in a similar issue. Using updateEditorValue solves the issue of a new row creating below, but with custom editor and custom cell where the dataType is a type of DataType.Object. 
after setting updateEditorValue, the Display component is receiving the 'value' as undefined and 'rowKeyValue'  also as 'undefined' but the same Table component passed 'rowKeyValue' as an empty object ({}) for editor. 

Kindly let me know I am going wrong anywhere. 

Thanks
