### ISSUE TITLE
Question: Performance issues

### ISSUE THREAD

**Issue by barucAlmaguer** [komarovalexander/ka-table#134]
Hi!
I'm using the library and works great and is easily customizable 😄 

I'm not sure if this is a ka-table performance issue or a pattern could be used to help improve performance (useMemo or the like):

# The problem

The table works super fast when using the default example with my custom styles:
![ka-table-performance-good](https://user-images.githubusercontent.com/16729556/109203004-3dfa0900-7769-11eb-9646-73dcd90b0e21.gif)

But just after I add some custom cell to the table, I run into performance issues (it slows badly, even with a small amount of rows):
![ka-table-performance-bad](https://user-images.githubusercontent.com/16729556/109203080-579b5080-7769-11eb-8f97-e9622c982d9b.gif)

I am using this pattern to add the custom cell:
```jsx
<Table
  {...tableProps}
  dispatch={dispatch}
  childComponents={{
    cell: {
      content: (cellProps) => {
        if (cellProps.column.key === ':inline-actions') {
          return <Grid columns={2} space='xxs' gap='xxs'>
            <Button variant='ghost' space='xxs' ><Icon source='far' icon='edit' /></Button>
            <Button variant='ghost' space='xxs' ><Icon source='far' icon='trash' /></Button>
          </Grid>
        }
      }
    }
  }}
/>
```

The amount of time to interact with every header sorting, scales from 6 seconds, to 10+ seconds (manual tests).

Is there a way to pass the custom cells straight into the data array to avoid running the logic inside cell.content for every cell?

At startup point I already know that I will render that couple of buttons on each last column's cell, and I think recalculating the needed component every time is causing this performance issue.

Probably Allowing to add custom cells directly to the Data array would allow to generate them at start time, boosting the performance.

Do you have any suggestion regarding this topic?

**Comment by komarovalexander** [comment]
Hi @barucAlmaguer,
I like the look of your UI.
I think adding rendered items to the data array would be antipatern you probably should not do that.

ka-table should work pretty fast, I did not have such cases before, so it is an interesting issue
can you provide some demo example with the reproduced issue, I can investigate it
also
I see in each cell you use `Grid` & `Button` components - which libraries do you use here? can they be the reason for bad performance? try to remove one of these components and compare the performance'
of course, you can use memorization see the demo for row https://komarovalexander.github.io/ka-table/#/many-rows-memo (for the cell it should be pretty similar) 
but I would recommend looking for the root cause

**Comment by barucAlmaguer** [comment]
Hi, thanks for the quick response!
I will try to setup a demo that mimics the performance issue.

The `Grid` and `Button` components do not seem to be the problem, 
digging a little more it seems like the icons are the ones causing bad performance.

For example, this responds very quickly (without the icons):
![ka-table-no-icons](https://user-images.githubusercontent.com/16729556/109213607-6b00e880-7776-11eb-8fd5-3b5899a6a4e0.gif)

I'll take a look at the memoization demo and come back to you, thanks

**Comment by barucAlmaguer** [comment]
https://codesandbox.io/s/confident-hooks-gwjb8?file=/src/components/KaTablePerformanceDemo.js

I made a minimal example creating an almost identical table, and It ran without any issue, even with the same pack of icons.
It's probably on my side (The inner workings of the "Icon" component).

I'll take a look but I think the issue may be closed as I pin-pointed the problem outside the library.

Thanks for your help!
