### ISSUE TITLE
A new row cannot be added to an empty table

### ISSUE THREAD

**Issue by registsys** [komarovalexander/ka-table#135]
We can't add new row when table haven't data.

[example](https://stackblitz.com/edit/table-add-row-js-ky82ru?file=Demo.js)

**Comment by registsys** [comment]
https://github.com/komarovalexander/ka-table/pull/136

**Comment by komarovalexander** [comment]
Hi @registsys ,
Thanks for finding that issue and proposing a pr to fix that. I will have a look at it today evening and will fix it soon. I will let you know if any updates

**Comment by komarovalexander** [comment]
@registsys you can use `6.7.2` version https://stackblitz.com/edit/table-add-row-js-cafwsr?file=Demo.js

**Comment by registsys** [comment]
Super fast!!! Thank you.
