### ISSUE TITLE
VirtualScrolling.scrollTop not working as expected?

### ISSUE THREAD

**Issue by jorgecuesta** [komarovalexander/ka-table#139]
Hi I was trying your component and try to figure out a way to trigger scroll to some row but didn't figure out a way by the row index, so looking the code see that I can sent the scrollTop inside of virtualScrolling, but when I try it insted of scroll I get a white space in the start of the table.

![Screen Shot 2021-03-19 at 2 16 35 PM](https://user-images.githubusercontent.com/9866992/111825393-cf1e5480-88bd-11eb-9fc0-ad28127191e1.png)

Here u can check how I'm trying to implement the scroll to row.

https://stackblitz.com/edit/table-many-rows-js-7cuk5c?file=Demo.js

**Comment by komarovalexander** [comment]
Hi @jorgecuesta,
Thanks for finding that!
I made a workaround for this case: https://stackblitz.com/edit/table-many-rows-js-2fyxub?file=Demo.js
I will keep this issue open and let you know if any updates

**Comment by jorgecuesta** [comment]
Thanks u so much @komarovalexander that work smooth!

**Comment by jorgecuesta** [comment]
@komarovalexander one big question about it, can you or the dev team behind it, see if there is a way to "scroll" by the row index or a keyReg to the desired row? something like react-virtualized https://github.com/bvaughn/react-virtualized/blob/master/docs/List.md
![Screen Shot 2021-03-19 at 5 27 00 PM](https://user-images.githubusercontent.com/9866992/111843907-5b3d7580-88d8-11eb-9573-b4ce29630cc7.png)

**Comment by komarovalexander** [comment]
do you need something like that: https://stackblitz.com/edit/table-many-rows-js-ybgqhd?file=Demo.js

**Comment by komarovalexander** [comment]
@jorgecuesta do you need something like that: https://stackblitz.com/edit/table-many-rows-js-ybgqhd?file=Demo.js

**Comment by jorgecuesta** [comment]
@komarovalexander that is the same I ask in first place here: https://github.com/komarovalexander/ka-table/issues/139#issue-836251346
I was looking for something like a prop in Table component that do this by me. I'm trying to do this also with grouping and is difficult to calculate where the row will be and also to know if the row is visible or not because of the group expand/collapse.

You can check my in progress attempt to get scroll to row with grouping here:
https://stackblitz.com/edit/table-many-rows-js-bjjvzo?file=Demo.js

**Comment by komarovalexander** [comment]
@jorgecuesta ah it is the tricky case - at this time table does not have built-in ability to do that, but it can be customized in different ways so the solution could be like this: https://stackblitz.com/edit/table-many-rows-js-zziojy?file=Demo.js

**Comment by komarovalexander** [comment]
regarding your question answer is: `scrollTop` is not so accurate name it just adds an empty line with height =  `scrollTop` for virtual scrolling and the table does not have built-in scroll abilities, they can be done as we discussed above

**Comment by komarovalexander** [comment]
more accurate case for equal row height: https://stackblitz.com/edit/table-many-rows-js-ofn9ah?file=Demo.js

**Comment by jorgecuesta** [comment]
@komarovalexander that work smooth! Thanks you very much! now I will look a way to "highlight" the row, my intention is do a "search" that when match rows you can go doing "next or prev" so it will moving the table focus over the results.

The idea behind that is a search like the browser but in a virtualized table.

**Comment by komarovalexander** [comment]
Just curious: why regular search in the table does not fit your requirement https://komarovalexander.github.io/ka-table/#/search ?

**Comment by komarovalexander** [comment]
I think to highlight word you can use this component https://github.com/bvaughn/react-highlight-words and return it from table.childComponents.cellText.content ( https://komarovalexander.github.io/ka-table/#/custom-cell )

**Comment by jorgecuesta** [comment]
@komarovalexander because the regular search is filtering the table and in my case the element that you match has some kind of "sequence" or context with the previous and next element, so to allow the user to see what they are looking and also preserve the context of the previous and next record of the match.

**Comment by komarovalexander** [comment]
Hi @jorgecuesta 
I've just added a good draft example for your feature https://stackblitz.com/edit/table-many-rows-js-hgf2wt?file=Demo.js , I hope it helps! 
Thanks for asking about that tricky case, I will wait until other requests before implementing this out of the box.
