### ISSUE TITLE
Question: Filter and Sorting logic

### ISSUE THREAD

**Issue by barucAlmaguer** [komarovalexander/ka-table#141]
Hi! I'm trying to implement the new features from 6.8.0 (custom Filter logic and custom Sorting logic), but the functions don't appear to be called when I sort any column 🤔 

I have custom components for the Head cells, and I trigger an `dispatch(updateSortDirection(column.key))` like this:

```
return <KaHeaderCell onClick={() => { dispatch(updateSortDirection(cellProps.column.key)) }}>
        <div className='title'>{cellProps.column.title}</div>
        {thisColumn.icon && <Icon source={thisColumn.icon.source || 'far'} icon={thisColumn.icon.name} />}
        <SortIcon direction={cellProps.column.sortDirection} />
      </KaHeaderCell>
``` 

which works great using the default sorting function (here we can see a "sort ascending" icon, and the sorted data works fine):
![Screenshot from 2021-03-23 17-37-13](https://user-images.githubusercontent.com/16729556/112232659-91436800-8bfe-11eb-9fdb-5c597077de8c.png)

But when I add the sorting function or filter function in the tableProps like this:
![Screenshot from 2021-03-23 17-30-43](https://user-images.githubusercontent.com/16729556/112232713-a7e9bf00-8bfe-11eb-8c3b-3797918b6e88.png)

they seem to be "ignored" by the table, it works using the default sorting mechanism.

I'm not even attempting to custom sort right now, it's just a console log to see if it reaches that line, but it never gets called.

When I attempt a codeSandbox with the most basic ka-table configuration, it works fine (console.logs my message), so I'm guessing there is an additional configuration needed to be done, but can't figure out which one.

do you know of some config that I may be ommiting that "skips" the custom sorting / filters?

Everything else seems to work fine (custom headers, custom cells, cellTexts, styles, etc)

**Comment by barucAlmaguer** [comment]
Update:

Generating a Demo in my project with the exact same code that works in code sandbox (a much simpler table than the one I'm working on), it doesn't work either 🤔 

I was expecting it to work being the same code, but it doesn't:
![Screenshot from 2021-03-23 17-48-14](https://user-images.githubusercontent.com/16729556/112233485-24c96880-8c00-11eb-9e5d-654e588b6c56.png)

Code:
```
import React, { useState } from "react";

import { ITableProps, kaReducer, Table } from "ka-table";
import { DataType, SortDirection, SortingMode } from "ka-table/enums";
import { DispatchFunc } from "ka-table/types";
const dataArray: any[] = [
  {
    id: 1,
    name: "Mike Wazowski",
    score: 80,
    prevScores: [59, 65, 70],
    passed: true
  },
  {
    id: 2,
    name: "Billi Bob",
    score: 55,
    prevScores: [60, 43, 50],
    passed: false
  },
  {
    id: 3,
    name: "Tom Williams",
    score: 45,
    prevScores: [62, 61, 60],
    passed: false
  },
  {
    id: 4,
    name: "Kurt Cobain",
    score: 75,
    prevScores: [63, 60, 71],
    passed: true
  },
  {
    id: 5,
    name: "Marshall Bruce",
    score: 77,
    prevScores: [72, 80, 79],
    passed: true
  },
  {
    id: 6,
    name: "Sunny Fox",
    score: 33,
    prevScores: [25, 45, 37],
    passed: false
  },
  {
    id: 7,
    name: "Alex Brzowsky",
    score: 48,
    prevScores: [50, 47, 43],
    passed: false
  }
];

const tablePropsInit: ITableProps = {
  columns: [
    {
      dataType: DataType.Boolean,
      key: "passed",
      style: { width: 90 },
      title: "Passed"
    },
    {
      dataType: DataType.String,
      key: "name",
      style: { width: 100 },
      title: "Naaamm"
    },
    {
      dataType: DataType.Number,
      key: "score",
      style: { width: 120 },
      title: "Score"
    },
    {
      dataType: DataType.Object,
      sortDirection: SortDirection.Ascend,
      key: "prevScores",
      style: { width: 120 },
      title: "Previous Scores"
    }
  ],
  data: dataArray,
  format: ({ column, value }) => {
    if (column.key === "prevScores") {
      return value.join();
    }
  },
  sort: ({ column }) => {
    console.log("validating sort function");
    if (column.key === "prevScores") {
      return (a, b) =>
        a[0] === b[0]
          ? 0
          : a[0] < b[0]
            ? column.sortDirection === SortDirection.Ascend
              ? -1
              : 1
            : column.sortDirection === SortDirection.Ascend
              ? 1
              : -1;
    }
  },
  rowKeyField: "id",
  sortingMode: SortingMode.SingleTripleState
};

const TestSorting: React.FC = () => {
  const [tableProps, changeTableProps] = useState(tablePropsInit);
  const dispatch: DispatchFunc = (action) => {
    changeTableProps((prevState: ITableProps) => kaReducer(prevState, action));
  };
  return (
    <Table
      {...tableProps}
      dispatch={dispatch}
    />
  );
};

export default TestSorting

```

**Comment by komarovalexander** [comment]
Hi @barucAlmaguer, 
custom sorting will not work in the case of '*remote' sorting mode, it also will not be called if the column does not have any sort direction. In the rest cases, it should work. I suppose it is a cache or for some reason, you have an old version of js files of the library. Please check that your node_modules/ka-table/Utils/SortUtils.js` file contains any `customSort` mention, and after that clear the cache in your browser

**Comment by barucAlmaguer** [comment]
Yes, Probably it was due to a cache problem in the browser, as I checked the version and node_modules and it was indeed the latest version.

The problem fixed itself so I guess it was some caching issue.

It's working great, thanks!
