### ISSUE TITLE
Adding New Row with default value

### ISSUE THREAD

**Issue by WZSE** [komarovalexander/ka-table#142]
I have a scenario, where I need to add a new row and get user input only for few cells & other should have some default value at runtime. (e.g. new row created time)

The default value for cell is being read by `rowData` in [CellComponent](url). But `NewRow` initialize this to empty object and I see no way to pass from a prop.

I may be missing a way to implement this if it's already available. If not, please add support and provide a demo.

Thanks.

**Comment by komarovalexander** [comment]
Hi @WZSE 
thanks for your question, really appreciate that. Here is a working example: https://stackblitz.com/edit/table-add-row-ts-4wwart?file=Demo.tsx

some comments: 
1) you have to return empty component for editor
```
          cellEditor: {
            content: props => {
              if (props.column.key === "column4") {
                return <></>;
              }
            }
          },
```
2) before calling `saveNewRow` you can set default value this way:
```
    // update editor value before saving (set default value for hidden editor on step1 )
    dispatch(updateEditorValue(newRowId, "column4", "my default value"));
    // save row value
     dispatch(
      saveNewRow(rowKeyValue, {
        validate: true
      })
    );
```

let me know if it works for you

**Comment by WZSE** [comment]
Hi, this is exactly what I'm looking for. Thank you, much appreciated.

**Comment by codeorelse** [comment]
@komarovalexander thanks for your example and your great work on ka-table in general. I'm just wondering how this would work if you have for example a dropdown where you want to have a default value when ShowNewRow, so the user can still change the value before actually saving to the server. How would that work then?
