### ISSUE TITLE
Resizing column "jumps" when all column widths add up to less than 100% of table width

### ISSUE THREAD

**Issue by joshuagish** [komarovalexander/ka-table#143]
https://stackblitz.com/edit/table-column-resizing-js-6xtzc3?file=Demo.js

This also causes the other columns to resize. This is not an issue if the table is scrollable.

**Comment by komarovalexander** [comment]
Hi @joshuagish interesting case, let me check

**Comment by komarovalexander** [comment]
@joshuagish good catch! Fixed in 6.8.1 https://stackblitz.com/edit/table-column-resizing-js-zr1owr?file=Demo.js
