### ISSUE TITLE
Question - Unable to extract data out of table

### ISSUE THREAD

**Issue by WZSE** [komarovalexander/ka-table#146]
Hi,

Sample fork here: https://stackblitz.com/edit/react-sg3yxj?file=src%2FApp.js

I'm trying to fetch table from db & perform crud operations. Initially table is empty, user creates a row. After that when user trying to save the records in db, I'm getting empty row in the getData method.

In my development code it's just prints empty array while I can data in table in UI.

Similar case with above demo link. However I after it's printing empty array, another rendering happens and if I'm debugging, I can see data property with rows. But that rendering goes with error message.

Edit: If I move the save action inside the dispatcher, I can see the rows in the prevstate property.  I have changed the dispatch into the following way.

 ```
changeTableProps((prevState) => {
            var props = kaReducer(prevState, action);
            if (action.type === SAVE_GRID) {
                saveData(props.data);
            }
            return props;
        });
```

I guess this is how I need to access data. Am I doing it correctly? kareducer is returning updated data, but I guess UI render for this action will be asynchronous. So is it fine to use the reducer return value?

**Comment by komarovalexander** [comment]
Hi @WZSE 

> I'm trying to fetch table from db & perform crud operations. Initially table is empty, user creates a row. After that when user trying to save the records in db, I'm getting empty row in the getData method.

it is because you're passing initial object tablePropsInit `kaPropsUtils.getData(tablePropsInit)` instead tableProps `kaPropsUtils.getData(tableProps)`

**Comment by WZSE** [comment]
Ah! such an embarrassing miss. Thank you.
