### ISSUE TITLE
Question: independent config for column isEditable (create vs update) 

### ISSUE THREAD

**Issue by barucAlmaguer** [komarovalexander/ka-table#150]
Hello, thanks for the great library! so far it has been working without problems.

I have a question, is there a way to customize the behaviour of the table for the "create row" and the regular rows independently?

the use case is:
imagine I have 4 fields:
- email
- name
- last name
- age

I want to be able to set those 4 fields when creating new rows, but when editing existing rows, I want to disable editing in some of them, so the behaviour would be like this:

- email: create only
- name: update/create
- lastName: update/create
- age: update/create

is there a way to complish this from the tableProps?

The only workaround I have found is to implement custom cells for each column and manage a lot of logic inside the custom cell.
- is the cell in edit mode? is it a New row or a regular row? which external option did I pass? (create/update), etc.

For default cells I think this is a little bit overkill, is there a way to accomplish this in a more clean way, with the tools provided from ka-table?

**Comment by komarovalexander** [comment]
Hi @barucAlmaguer 
your case is quite widespread and thanks for asking that, there is a workaround: 
```
          cell: {
            content: props => {
              if (props.rowKeyValue !== newRowId && props.column.key === "column1") {
                return <CellText {...props}/>
              }
            }
          },
```
newRowId  and CellText are available in ka-table library
link to example 
https://stackblitz.com/edit/table-add-row-ts-fxbqjy?file=Demo.tsx

**Comment by barucAlmaguer** [comment]
great thanks!
I think I can work with that.

still, if it's a widespread use-case, I think it would be great if supported by the main API (tableProps)

but for now this will do the trick

**Comment by komarovalexander** [comment]
Hi @barucAlmaguer there is another one solution with custom reducer 
```
const customReducer = (prevState, action) => {
  if(action.type === ActionType.OpenEditor && action.columnKey === "column1"){
    return prevState; 
  }
  return kaReducer(prevState, action);
};
```
https://stackblitz.com/edit/table-add-row-ts-ywvfvh?file=Demo.tsx

I think this is a better one. 
I do not have plans to implement `isEditableNewRow` option at this time, I will wait for further requests, at this time I'm closing the issue. Thanks for highlighting that!
