### ISSUE TITLE
Table search fails on non-string values

### ISSUE THREAD

**Issue by WZSE** [komarovalexander/ka-table#151]
Hi,

It's great library with tons of demos. Thank you for that.

I have a search box where on selection, I'll send numeric values to search action. This fails on toLowerCase() conversion.

Issue link: https://stackblitz.com/edit/table-search-js-p3mjmx?file=Demo.js

The workaround I can think of is, sending the search item in custom string and handling it in search property function. But this would fail on complex objects scenario. 

Is there a better way? or can this be improved to send some objects and deal it in search function?

**Comment by komarovalexander** [comment]
Hi @WZSE can you do value.toString() before passing it to the search?

**Comment by WZSE** [comment]
Hi,

I could do that. But if the value becomes complex object with multiple
properties, wouldn't it fail?

Or even for big object I can stringify into json and parse in search method
like angular material table filter.


I was wondering if there is some other way. If not, thank you, we can close
this issue.

Thanks

**Comment by komarovalexander** [comment]
At this time search text can be a string value.  Do you have real use case when you need complex object in your project? ka-table also provides filterRow for more detailed search by particular colums

**Comment by WZSE** [comment]
My search box is in different file and I would not get to know the columns. Hence I couldn't use `UpdateFilterRowValue`

I have also looked at extendedFilter that's using `react-filter-control`. But I need to use project UI components so couldn't utilize it.

Made a change to illustrate a simple object than a number with possible workaround: https://stackblitz.com/edit/table-search-js-j5kbzs?file=Demo.js

**Comment by komarovalexander** [comment]
Hi @WZSE 
actually, `extendedFilter` should be your choice because it can work with any other UI components and without them. see comments 1-4 in example https://stackblitz.com/edit/table-search-js-a3r6pp?file=Demo.js

**Comment by komarovalexander** [comment]
Btw, Thanks for highlighting that! I've found a couple of mistakes in the docs, because of your issue. `search` can take `searchText` as a parameter and it can be string only. For more complex search abilities you have to use `extendedFilter`

**Comment by WZSE** [comment]
Yeap, That's what I am looking for. Thanks for the demo. Can be closed.
