### ISSUE TITLE
Customize "search" action

### ISSUE THREAD

**Issue by barucAlmaguer** [komarovalexander/ka-table#152]
Hello!

Is there a way to customize the global search action behaviour?

As far as I know, there are 2 ways to implement searches inside the table data:

1. per-column search (implemented setting the "search" field of the TableProps), total customization of the search behaviour
2. global search (implemented by triggering a "search" action like this: `dispatch((search('some text')))` (not fully customizable, searching in plain cell values).

My use case is this:
I have a working table, which has data with this shape:
```javascript
[
  {id: '1', column1: 'test', column2: {id: '10', label: 'label-1'}},
  {id: '2', column1: 'test 2', column2: {id: '11', label: 'label-2'}},
  {id: '3', column1: 'test 3', column2: {id: '12', label: 'label-3'}}
]
```

as of now, I have implemented successfully a column-based search on both columns, because it's customizable, but the global search only works for data in `column1`.

Is there a way I can pass a "globalSearch" function to the tableProps, or a "searchFunction" callback to the search action to allow me to customize the behaviour?

**Comment by WZSE** [comment]
Probably the similar scenario https://github.com/komarovalexander/ka-table/issues/151 we had discussed yesterday. So please check it out

**Comment by barucAlmaguer** [comment]
Yes, I think the solution to #151 also fits my needs, thanks!

**Comment by komarovalexander** [comment]
Ok. +1 :-)

**Comment by komarovalexander** [comment]
@barucAlmaguer your case is a bit easir because you have a string in searchText but object value in the column, you can also write like this 
```
 search: ({ searchText, rowData, column }) => {
    if (column.key === 'score'){
      return (searchText === rowData.score.value);
    }
  },
```
https://stackblitz.com/edit/table-search-ts-p6bwch?file=Demo.tsx

**Comment by komarovalexander** [comment]
btw if you write column 
```
  columns: [
    { key: 'column2.label', title: 'Label', dataType: DataType.String },
//...
  ],
```
Search should work automatically for column2 without additional logic
