### ISSUE TITLE
Setting column widths with <colgroup/>

### ISSUE THREAD

**Issue by Boorj** [komarovalexander/ka-table#153]
There's quite interesting native workaround to set widths of many columns at once.

```html
<table>                                <table>
    <colgroup>                             <!--<colgroup>                     -->
        <col style="width: 20px">          <!--    <col style="width: 20px">  -->
        <col style="width: 30px">          <!--    <col style="width: 30px">  -->
        <col style="width: 100px">         <!--    <col style="width: 100px"> -->
        <col style="width: 200px">         <!--    <col style="width: 200px"> -->
    </colgroup>                            <!--</colgroup>                    -->
    <tbody>                                <tbody>
    <tr>                                   <tr>
        <td>1</td>                             <td style="width: 20px">1</td>
        <td>2</td>      <!--COMPARE-->         <td style="width: 30px">2</td>
        <td>3</td>                             <td style="width: 300px">3</td>
    </tr>                                  </tr>
    <tr>                                   <tr>
        <td>4</td>                             <td style="width: 20px">4</td>
        <td>5</td>                             <td style="width: 30px">5</td>
        <td colspan="2">6</td>                 <td style="width: 300px" colspan="2">6</td>
    </tr>                                  </tr>
    </tbody>                               </tbody>
</table>                               </table>                           
                   
```

This code works well, natively supported and no need to set `style="width: XXXpx"` to each sell of the table.

@komarovalexander , what do you think is it worth to be implemented? Or, probably there were plans to embed this feature in future?

Also, is there a need to define all widths of `td's`? In fixed layout only the first row could be definitive for all widths. I assume that there we might encounter a pitfall in chunked multirows rendering (1M rows). But.. there also could be workarounds, I suppose.

**Comment by komarovalexander** [comment]
Hi @Boorj great proposal, I will add ability to set colgroup option in next releases, lets keep this issue open.
I will not change current behavior it will be just a new option.
 Regarding

> Also, is there a need to define all widths of td's? In fixed layout only the first row could be definitive for all widths. I assume that there we might encounter a pitfall in chunked multirows rendering (1M rows). But.. there also could be workarounds, I suppose.

you should not render 1M rows, table have pagination and virtual scrolling😉

**Comment by Boorj** [comment]
> colgroup option in next releases
Good news! 

>table has pagination and virtual scrolling
yes, that was exactly the point. I haven't look under the hood what do you use in virtual scrolling, so idea was that something might go wrong in the case of using `<colgroup>` with virtual scrolling. Probably you produce several tables for each cached chunk.

Meanwhile, I'm using next workaround.
Created a clone of `Table.tsx` with component, containing `extraOpts` prop.

`// TableWithColGroups.tsx`
![image](https://user-images.githubusercontent.com/2145313/119216218-a8b6a880-bafc-11eb-80f0-3bcb40dfc447.png)

And inject that mutated Table as TableWrapper content this way:

`// the file with invocation of ka-table's Table`
![image](https://user-images.githubusercontent.com/2145313/119216279-077c2200-bafd-11eb-86f0-2c69a6c068f1.png)

Everything works like a charm with `table-layout: fixed;`

**Comment by komarovalexander** [comment]
Hi @Boorj is colgroup something critical for you? Or it is for research purpose?

**Comment by Boorj** [comment]
Thanks for asking. Fortunately - no. I have found workaround (as described above). So now it works, and i will just wait for next releases. I realize, that any adding extra options is more architectural issue, not supposed to be hot fixed. 
Anyway, this seems to make some speed boost, i will probably try to profile the performance.

**Comment by komarovalexander** [comment]
Hi @Boorj could you please check how the proposed workaround can work when Grouping is enabled https://komarovalexander.github.io/ka-table/#/grouping

**Comment by Boorj** [comment]
> Hi @Boorj could you please check how the proposed workaround is working when Grouping is enabled https://komarovalexander.github.io/ka-table/#/grouping
Sure!
Cloned Table and TableWrapper and hardcoded injection of `<colgroup/>` in TableWrapperWithCols.

Feel free to play around here: https://stackblitz.com/edit/table-grouping-ts-d7tdg3?file=TableWrapperWithCols.tsx

But from my point I suppose, that another pitfall will be during handling of columns reorder or another operations with columns.

**Comment by komarovalexander** [comment]
Hi @Boorj 
it was finally fixed in v7.0.0
the column now has additional properties:
1) `width` which is actually syntax sugar for `colGroup.width`
2) `colGroup` - place where all attributes for col group can be set

Thanks for highlighting that tricky moment I was considering improving that but was not sure if people care about it - this issue changed my mind. Furthermore, colgroup is useful for grouped column resizing - just styles for each cell wasn't effective in that case

**Comment by Boorj** [comment]
@komarovalexander Thank you! Great! Appreciate a lot

**Comment by Boorj** [comment]
btw, @komarovalexander have you checked out if this change increased performance?

**Comment by komarovalexander** [comment]
Hi @Boorj I did not. This feature was very useful for https://komarovalexander.github.io/ka-table/#/grouped-columns implementation
