### ISSUE TITLE
[Request] support override props on columns to override table level props

### ISSUE THREAD

**Issue by TimNZ** [komarovalexander/ka-table#155]
It looks like table prop sortingMode is passed to all HeadCell.

Can you support a 'sortingMode' prop on columns that overrides the table prop?

This would eliminate need for a custom HeadCell for columns I don't want sorting enabled.

May as well do that for 'columnResizing', 'columnReording' on columns,
and 'editingMode' for data cells.

Reduces the need for custom content just to disable some things at a column/row level.

Let me know if you want me to do a PR.

**Comment by komarovalexander** [comment]
@TimNZ great idea with the pr - don’t hesitate to create it, I will review it, and it will be merged

Btw for editing and resizing column already has

```
public isEditable?: boolean;  
public isResizable?: boolean;

```

**Comment by TimNZ** [comment]
Ahh thanks.  I'll do better at reading through the docs.

**Comment by TimNZ** [comment]
Will submit PR
