### ISSUE TITLE
Is it possible to validate duplicated values?

### ISSUE THREAD

**Issue by registsys** [komarovalexander/ka-table#158]
```
validation: props => {
    if (props.column.key === 'name') {
        const { value, data } = props;
        if (!value) {
            return `Value can't be empty`;
        }
        if (data.find(it => it.name === value)) {
            return `Duplicated name: "${value}"`;
        }
    }
}`

```

**Comment by komarovalexander** [comment]
Hi @registsys , Thanks for asking that. You can define getValidation 
```
const getValidation = (data: any[]) => {
  return ({ column, value }) => {
   if (props.column.key === 'name') {
        const { value, data } = props;
        if (!value) {
            return `Value can't be empty`;
        }
        if (data.find(it => it.name === value)) {
            return `Duplicated name: "${value}"`;
        }
    }
  };
};
```
and pass it results to table
```
   <Table
        {...tableProps}
        dispatch={dispatch}
        validation={getValidation(tableProps.data)}
      />
```
at this time it is probably the best way to do that. If you have any proposals I'm always open to them! Thanks!

Demo: https://stackblitz.com/edit/table-validation-ts-qtdfvn?file=Demo.tsx

**Comment by registsys** [comment]
Hi, Alexander. Thank you for your quick answer. I tried your demo example and I see that it  behaves strange - when I click to any input in the score column, each clicked field marks as invalidate

![image](https://user-images.githubusercontent.com/42716494/120430147-39a04600-c37f-11eb-9d56-3bdc24d53c37.png)

**Comment by registsys** [comment]
Also, I tried to apply this approach to demo with adding new row and it (approach) seems not working. Could you check?

https://stackblitz.com/edit/table-add-row-js-yfhfrs?file=Demo.js

**Comment by registsys** [comment]
The demo with row editing does not work, too.

https://stackblitz.com/edit/table-editing-row-js-srwp79?file=Demo.scss

**Comment by komarovalexander** [comment]
> Hi, Alexander. Thank you for your quick answer. I tried your demo example and I see that it behaves strange - when I click to any input in the score column, each clicked field marks as invalidate

this is because instead of `data.find(it => it.name === value)` you need another condition: `data.find(it => it.score === value && rowData[rowKeyField] !== it[rowKeyField])`
example updated: https://stackblitz.com/edit/table-validation-ts-qtdfvn?file=Demo.tsx

**Comment by komarovalexander** [comment]
For adding new row and editing row: add validation function to state as well 
```
     kaReducer(
        { ...prevState, validation: getValidation(tableProps.data) },
        action
      )
```

**Comment by registsys** [comment]
Thanks a lot for your help.
