### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by korotkevics** [komarovalexander/ka-table#162]
Hi!
And one more question: would you suggest a way to disable manual sorting (do nothing when a user clicks on a column header) while keeping the "passive" single column based sorting?

**Comment by komarovalexander** [comment]
https://komarovalexander.github.io/ka-table/#/sorting-modes Sorting has singleRemote mode - this is what you need)

**Comment by korotkevics** [comment]
Thanks! It requires pre-sorting :(

**Comment by komarovalexander** [comment]
I got what you need, you want to prevent sorting change by click 
here it is: https://stackblitz.com/edit/table-sorting-ts-4vkqot?file=Demo.tsx 
you need to disable it in dispatch:
```
 const dispatch: DispatchFunc = action => {
    // don't change sort direction
    if(action.type === ActionType.UpdateSortDirection) return;
    changeTableProps((prevState: ITableProps) => kaReducer(prevState, action));
  };
```
does it work for you?

**Comment by korotkevics** [comment]
Thanks, it's working great!
