### ISSUE TITLE
Consider exposing filtering actions

### ISSUE THREAD

**Issue by korotkevics** [komarovalexander/ka-table#163]
I've wanted to wire in a custom widget manipulating filters on the table and I've handled it outside of ka-table (I am dispatching my own actions that impact what data is consumed by ka-table).
It'd be nice if ka-table instead exposed a simple action allowing to do the same thing, for example, an action could be accepting a filter such as,

```ts
interface SelectRowFilter {
  column: string
  condition: Function
}

interface UnselectRowFilter {
  column: string
  condition: Function
}

dispatch(selectAction({"name", value => value.startsWith("A")}:SelectRowFilter);
dispatch(selectAction({"name", value => value.equals("Alex")}:SelectRowFilter);
dispatch(unselectAction({"age", value => value >= 20}:UnselectRowFilter);

<MyCustomIndependentWidget onClick={foo => dispatch(selectAction({"foo", value => value < 0}))/>
```
I am not sure if the syntax is correct, but I think you get the idea.
In general, again, great job, thank you!

**Comment by komarovalexander** [comment]
in the ka-table you can write your own actions and extend the reducer logic as well 
http://ka-table.com/docs_action.html#custom-actions
http://ka-table.com/docs_reducer.html#custom-reducer

**Comment by komarovalexander** [comment]
btw built-in selectAllVisibleRows & selectAllFilteredRows actions do not work for you?

**Comment by korotkevics** [comment]
> in the ka-table you can write your own actions and extend the reducer logic as well
> http://ka-table.com/docs_action.html#custom-actions
> http://ka-table.com/docs_reducer.html#custom-reducer

Thanks, I will have a look at it!
