### ISSUE TITLE
cellText.content cannot be empty string

### ISSUE THREAD

**Issue by 98o718** [komarovalexander/ka-table#165]
I have NaN as raw value and transform it to empty string in cellText.content, but table display raw value because `content || formatedValue || <>&nbsp;</>` in CellText

**Comment by 98o718** [comment]
0 will also be ignored

**Comment by komarovalexander** [comment]
Hi @98o718
you can wrap the result into the empty component like `return <>0</>;`
https://stackblitz.com/edit/table-custom-cell-ts-ardafs?file=Demo.tsx

**Comment by 98o718** [comment]
Thank you!
