### ISSUE TITLE
Why the package on npmjs doesn't have dependencies in package.json?

### ISSUE THREAD

**Issue by timocov** [komarovalexander/ka-table#166]
The published package doesn't have `dependencies` list https://unpkg.com/browse/ka-table@6.9.0/package.json even if it has them https://github.com/komarovalexander/ka-table/blob/master/package.json#L7. Is there any reason for that? For now https://bundlephobia.com/package/ka-table@6.9.0 warns about that and most likely the bundle size might be different (or at least self-size)

![image](https://user-images.githubusercontent.com/3112183/123259665-a45f2000-d4ec-11eb-8a21-cc344e3ffb43.png)

**Comment by timocov** [comment]
https://github.com/komarovalexander/ka-table/commit/3da526a653e672a324a8becb95b22f7edd84aec6 it seems that removing dependencies from target `package.json` was added a long time ago but I don't really understand why it was needed.

**Comment by komarovalexander** [comment]
Hi @timocov thanks for your question.
This repo contains ka-table demo site code https://komarovalexander.github.io/ka-table/#/overview - this website is a react application and all these dependencies are required for it. 
ka-table library is just a react library and none of these dependencies are required to make it work (except react). It even can work without typescript

**Comment by timocov** [comment]
@komarovalexander thanks for the answer.

> ka-table library is just a react library and none of these dependencies are required to make it work (except react).

How the consumer of this library might understand this? The package states that it has no dependencies, but actually it has at least 1 (who knows what else and what versions of them).
Also, you might use some features of the new react framework which aren't exist in the previous one, and based on that I'm as a consumer of ka-table library cannot know that from the package itself, I have to go to the source code and try to figure out what exactly versions it uses (and as you stated, all these deps are from the website and it's tricky to understand what the min version or range of versions the library supports).

For me, all website related deps should be in the website's folder where they will be installed due the deploy stage.

**Comment by komarovalexander** [comment]
> Also, you might use some features of the new react framework which aren't exist in the previous one, and based on that I'm as a consumer of ka-table library cannot know that from the package itself


Just install it and if there are any issues with your react version let me know about it creating a github issue it this repo.

**Comment by timocov** [comment]
> Just install it and if there are any issues with your react version let me know about it creating a github issue in this repo.

@komarovalexander I don't think that anyone will do that on daily basis on every update of the library (we have semver and the dependency tree for that). But anyway thanks for your answer!

**Comment by komarovalexander** [comment]
@timocov please provide at least one real live example where you have an issue for your react version. I think issue with https://bundlephobia.com/package/ka-table@6.9.0 is that I remove dependencies node completely I think if I just pass empty settings to dependencies it should be fixed on that side. 
Also give me example of react library package where react dependency is specified. I think your proposed solution should bring more cons than pros
Thank

**Comment by 98o718** [comment]
For example, https://unpkg.com/browse/react-window@1.8.6/package.json, different versions of react are listed as peerDependencies

**Comment by komarovalexander** [comment]
It is nice, but it is not dependencies field, @timocov @98o718 do you have some issues when it is not possible to use ka-table with some specific react version and peerDependencies would save your time?

**Comment by 98o718** [comment]
At the moment there are no problems, but they may arise if you start using the features of the react that are available only in the latest version. So it would be nice to add the `^ 15.0.0 || ^ 16.0.0 || ^ 17.0.0` versions to the peerDependencies array. It would be a kind of agreement between the developer and the consumers of the library that it will work with React version 15.

**Comment by komarovalexander** [comment]
Got it, thanks, I will add it in next releases. I need to find oldest version of react which support this component. I tested it on latest 16 and 17. But it should work with older version as I don’t use new features of react here to avoid breaking changes for current users

**Comment by komarovalexander** [comment]
`ka-table` is compatible with react v16.8.0 and above 

js: https://stackblitz.com/edit/table-overview-js-j6kf6d?file=Demo.js
ts: https://stackblitz.com/edit/table-overview-ts-pxnxfg?file=Demo.tsx

I will add this info to peerDependencies in one of the next releases, probably in July. Thanks to everyone for highlighting that

**Comment by komarovalexander** [comment]
`peerDependencies` has been added https://bundlephobia.com/package/ka-table@6.11.5
