### ISSUE TITLE
Setting sortDirection breaks row reordering

### ISSUE THREAD

**Issue by joshuagish** [komarovalexander/ka-table#169]
Reproduction steps: You can load the [sorting logic example](https://stackblitz.com/edit/table-sorting-custom-logic-ts?file=Demo.tsx) and add `rowReordering: true` to tablePropsInit. 

You are not able to reorder because `sortDirection` is set.
Should the sort be removed when the user reorders or should this decision be left to the devs?

**Comment by komarovalexander** [comment]
Hi @joshuagish I will provide workaround tomorrow. I think sorting works as expected - it sorts data according to settings. Lets check workaround first and after we will decide if it is worth to add one more sorting mode for that case

**Comment by komarovalexander** [comment]
here is a workaround 
https://stackblitz.com/edit/table-sorting-custom-logic-ts-qafy7p?file=Demo.tsx 
```
  // 1. use SortingMode.SingleRemote to disable local sorting logic
  sortingMode: SortingMode.SingleRemote
};

// 2. Reducer
const customReducer = (prevState, action) => {
  const newProps = kaReducer(prevState, action);
  if (action.type === ActionType.UpdateSortDirection) {
    const columnKey = action.columnKey;
    // sort data after each UpdateSortDirection
    const data = kaPropsUtils.getData({
      ...newProps,
      sortingMode: SortingMode.Single
    });
    return { ...newProps, data };
  }
  if (action.type === ActionType.ReorderRows) {
    newProps.columns.forEach(c => (c.sortDirection = undefined));
    return newProps;
  }
  return newProps;
};
```

**Comment by komarovalexander** [comment]
I think that it should be handled by devs at this time, but maybe if there is more request for that I could be implemented in `ka-table` out-of-the-box

**Comment by bay-jacewhitten** [comment]
@komarovalexander its is 3 years later... is this solution still valid? I am currently in need of sorting and reordering.
