### ISSUE TITLE
Group header columns

### ISSUE THREAD

**Issue by korotkevics** [komarovalexander/ka-table#170]
Hello!

Would you be able to suggest a way of adding an extra header above the normal header grouping columns of the normal header?

For example, there'd be columns such as "Yesterday", "Today", "Tomorrow" grouped as "Weather", "Name" grouped as "Name", "Max", "Min" grouped as "Temperature". Just a random example.

**Comment by komarovalexander** [comment]
Hi @korotkevics at this time there is no built-in functionality in ka-table to do that. 
I think it is the candidate for the next releases, lets keep this issue opened, I think I will be able to release it at the end of this summer
Now you can implement a custom header row. Feel free to contact me if you need any help with that

**Comment by korotkevics** [comment]
> Hi @korotkevics at this time there is no built-in functionality in ka-table to do that.
> I think it is the candidate for the next releases, lets keep this issue opened, I think I will be able to release it at the end of this summer, but I will let you know if any updates on that
> Now you can implement a custom header row. Feel free to contact me if you need any help with that

Thank you, take your time:) 

Basically, I could write a custom `HeadRow`, right https://github.com/komarovalexander/ka-table/blob/master/src/lib/Components/HeadRow/HeadRow.tsx

**Comment by komarovalexander** [comment]
you can use child components: http://ka-table.com/docs_props.html#childcomponents headRow

**Comment by komarovalexander** [comment]
@korotkevics it is available starting from v: 7.0.0
Demo: https://komarovalexander.github.io/ka-table/#/grouped-columns
