### ISSUE TITLE
Expose validation as dispatchable action

### ISSUE THREAD

**Issue by WZSE** [komarovalexander/ka-table#177]
Currently I have this grid that contains almost all columns editable all the time. I'm using CellEditorString with custom onBlur. Also some mandatory field validation.

Now this validation kicks in only when SaveNewRow/SaveRowEditors. It would be nice if that's exposed as an action in reducer, so I can trigger that explicitly which could display the validation messages.

**Comment by komarovalexander** [comment]
Hi @WZSE I already opened a pr. I will merge it later next week - at this time I have some issues with Travis CI hopefully they will solve it soon.
If you need it immediately you can create a custom reducer for that action https://github.com/komarovalexander/ka-table/pull/178/files#diff-fa7a5559cb192411f4e172917bc53951a25e473127ec47f8c631a16f72fffb27R311

**Comment by WZSE** [comment]
Great, I have used the above commit as custom dispatcher action. Thanks for the quick update.

However once I start using this, I see the workflow is not fitting for what I'm expecting. Perhaps this is a different issue, but the workflow is:

1. I have to customize `Cell` attribute of table to display `CellEditorString` all the time.
2. Perform validation in some custom button click
3. Now `editableCells` have validation message filled.
4. But since I'm using custom cell to display editable textboxes all the time, custom cell content is rendered instead of CellEditor. So I'm missing the `CellEditor`->`CellEditorState`->`CellEditorValidation`->`CellEditorValidationMessage`.
5. Captured validation message is not displayed.

Is there a simple step I'm missing here?

Repo: https://stackblitz.com/edit/table-add-row-js-sdzxku?file=Demo.js

**Comment by komarovalexander** [comment]
Hi @WZSE 
I think you don't need to show `CellEditorString` in the `Cell` - it is better to open editors using `editableCells`

check comments in this example https://stackblitz.com/edit/table-add-row-js-dtrlfz?file=Demo.js

is it something you are looking for? let me know if you need something else here

**Comment by WZSE** [comment]
Yeap, exactly what I'm looking for. Thank you for much help

**Comment by komarovalexander** [comment]
Hi @WZSE starting from `7.1.0` there is a new API, which could make code easier to read, check this demo https://komarovalexander.github.io/ka-table/#/editing-table maybe this solution will be even better for you

**Comment by WZSE** [comment]
Cool! Instead of useEffect, I'll use this.

Although it's not my requirement, don't you see another action called `closeAllEditors` would be another fine addition?
