### ISSUE TITLE
Add new row at index

### ISSUE THREAD

**Issue by efitzkiwi** [komarovalexander/ka-table#183]
It seems like showNewRow only adds a new row to the top of the table. I'm currently trying to create excel-like functionality where right-click brings up context menu for the row, and there is an option to insert a new row above the selected row:
![image](https://user-images.githubusercontent.com/9599423/138204434-4a5cb3c4-701d-4406-a507-15f293760ccc.png)

Context menu seems doable, but inserting a row at index "n" does not.

**Comment by komarovalexander** [comment]
Hi @KillerKiwiJuice. I think in your case you can simply add an empty row object (id is required) the required position in table data. And after that call “openRowEditors“ for that row. Let me know if you need help with that
