### ISSUE TITLE
Virtualized scroll dynamic height

### ISSUE THREAD

**Issue by KillerKiwiJuice** [komarovalexander/ka-table#185]
Hello, I would like the Ka-Table height to scale with its parent container when using virtualized scrolling AKA use 100% of parent container, even if parent is resized.

I have tried using SizeMe (https://github.com/ctrlplusb/react-sizeme) My final setup is this, but does not work.
```        
       <SizeMe>
          {({ size }) => 
            <Table 
              {...this.state.tableProps}
              width={''+size.width}
              height={''+size.height}
              dispatch={this.dispatch}
              childComponents={{
                tableWrapper: {
                  elementAttributes: () => ({ style: { height: "800px" }})
                },
              }}
            />
          }
      </SizeMe>
```

https://user-images.githubusercontent.com/9599423/139798989-c6af2bc1-a53c-42ec-bec1-9add91943e9f.mp4

**Comment by komarovalexander** [comment]
Hi @KillerKiwiJuice 
I think issue is here

childComponents={{
                tableWrapper: {
                  elementAttributes: () => ({ style: { **height: "800px"** }})
                },
              }}
              
Try to set size.height here or remove this settings at all

**Comment by komarovalexander** [comment]
Also try to update bodyHeight in virtualScrolling option http://ka-table.com/docs_props.html#virtualscrolling

**Comment by KillerKiwiJuice** [comment]
This code worked :) tnks

```
        <SizeMe>
          {({ size }) => 
            <Table 
              {...this.state.tableProps}
              height={''+size.height}
              dispatch={this.dispatch}
            />
          }
        </SizeMe>
```
