### ISSUE TITLE
Strange keyboard navigation with PopperJS

### ISSUE THREAD

**Issue by KillerKiwiJuice** [komarovalexander/ka-table#186]
There is a strange issue, I am not sure if it's related with Ka-Table, PopperJS or Blueprint react. But I have narrowed it down to this component: (https://blueprintjs.com/docs/#core/components/menu). Blueprint Menu uses PopperJS.

Issue description: when a cell is focused, then "enter" key is pressed, the dispatch function calls OpenEditor immediately followed by CloseEditor, which means "enter" cannot open cell editor.

Intended behavior: "enter" key opens cell editor and allows user to edit data

Here is a demo showcasing the bug. Try removing the `<div> above <Table>` ... issue is fixed
https://stackblitz.com/edit/table-keyboard-navigation-js-2iqbfu?file=Demo.js

P.S. The project is amazing... tnks

**Comment by komarovalexander** [comment]
Hi @KillerKiwiJuice 
when Editor loses focus ka-table calls CloseEditor if EditingMode.Cell is enabled
For some reason when you press enter, the editor loses focus on the Editor element after clicking,

You can fix it adding `e.stopPropagation();` for `onKeyUp`
https://stackblitz.com/edit/table-keyboard-navigation-js-yygtys?file=Demo.js

**Comment by komarovalexander** [comment]
Thanks for highlighting that, I've added the note to the documentation
