### ISSUE TITLE
Multiple Tables in Redux

### ISSUE THREAD

**Issue by amoran** [komarovalexander/ka-table#198]
Is it currently possible to have multiple different tables while using the dispatch from redux?  If so, how do you specify which table the actionCreator should be referencing?  

For example, specifying which table is loading if multiple exist in one app:

`dispatch(showLoading())`

**Comment by komarovalexander** [comment]
Hi @amoran 
I think there should be a way (for example you can have separate dispatch for each table), can you share your example of where you need to implement that?
