### ISSUE TITLE
Using Treemode with virtual scrolling and dynamic height causes scroll wiggle

### ISSUE THREAD

**Issue by Surfkeks** [komarovalexander/ka-table#202]
Hello, 

first of all thanks for this amazing library! I used it a lot the last month and really like it. 
I am building a database that uses virtual scrolling, dynamic row height and treemode. 

**Sadly, as soon as i enable treemode, the virtual scrolling jumps around a lot and the whole table is unusable.**

I could reproduce the issue with your demos: https://stackblitz.com/edit/table-tree-mode-ts-8fzzw8?file=Demo.tsx
(but on a big table it is way worse)

I tried solutions like closing or opening all trees on startup, changing the estimatedItemSize and increasing the tbodyHeight.

I appreciate your help,

greetings from Germany!

**Comment by komarovalexander** [comment]
Hi @Surfkeks can you share an example with the tree mode? Looks like this is not enabled in your example https://stackblitz.com/edit/table-tree-mode-ts-8fzzw8?file=Demo.tsx thanks!
