### ISSUE TITLE
Material UI Support / Examples

### ISSUE THREAD

**Issue by normand1** [komarovalexander/ka-table#204]
Hi, I'm really enjoying using this project, but I'm struggling with integrating it with the rest of the Material UI design system I'm using: https://mui.com/material-ui/react-table/

I've updated all of the child components with the expected classes for MUI, but I'm, not seeing the styles reflected in ka-table.
Any help or suggestions for integrating with MUI would be appreciated!

ps. I've checked out the [docs for material theming](https://komarovalexander.github.io/ka-table/#/material), but that appears to be a different project.

**Comment by komarovalexander** [comment]
thanks for the issue, I use mui in the demo now https://komarovalexander.github.io/ka-table/#/material
