### ISSUE TITLE
How can we provide select all checkboxes and filtering checkbox items with textbox at the top in autocomplete manner in header filter over the react table grid

### ISSUE THREAD

**Issue by SRGajjala** [komarovalexander/ka-table#207]

**Comment by komarovalexander** [comment]
Hi @SRGajjala 
this is a good question I will keep it open for a while. 
At this time there is no build-in functionality for that, but you can implement it on your own manner, you just need to override childComponent for popupContent

**Comment by komarovalexander** [comment]
#187 similar question

**Comment by komarovalexander** [comment]
Hi @SRGajjala in v11.0.0 search has been added to the HeaderFilter https://komarovalexander.github.io/ka-table/#/header-filter-logic . As for "select all checkbox" - I do not have plans to implement it yet, I will wait for further requests before implementing that
