### ISSUE TITLE
Pagination Not Updated During Group Mode Expansion/Contraction

### ISSUE THREAD

**Issue by gerryfletch** [komarovalexander/ka-table#214]
Hello, amazing library! Appreciate all the work that's gone into it.

I'm using fixed pagination, i.e. `paging: { enabled: true, pageSize: 10 }`, but when using column groups, if I contract the grid down to 1 or 2 rows, the pagination numbers have not updated, and visiting the 2nd page results in an empty grid.

Ideally, the paging would reflect the number of visible rows and update when the collapse/expand event fires.

**Comment by komarovalexander** [comment]
Hi @gerryfletch can I ask you to provide an example for your case, for example on stackblitz: https://stackblitz.com/edit/table-paging-ts?file=Demo.tsx

**Comment by gerryfletch** [comment]
Sure! Here you go:

https://stackblitz.com/edit/table-paging-ts-q8alm3?file=Demo.tsx

I changed the data array to have the same value for column 4 then added `  groups: [{ columnKey: "column4" }],` to the config.

If you just collapse the row, and then navigate to any of the pages :)

**Comment by komarovalexander** [comment]
this is good catch

**Comment by komarovalexander** [comment]
fixed in 7.3.5 https://stackblitz.com/edit/table-paging-ts-2qredp?file=Demo.tsx

**Comment by gerryfletch** [comment]
Thank you so much for the quick fix! Really appreciate it
