### ISSUE TITLE
Empty state for remote data

### ISSUE THREAD

**Issue by olliejm** [komarovalexander/ka-table#221]
Perhaps I missed something but I don't see any way to provide some JSX to render when the table has an empty data array? For remote fetched data it's possible that there can be no results, if you're using some sort of filtering, so I think it should be possible to optionally define what should be rendered within the table body when the data array is empty

**Comment by komarovalexander** [comment]
Looks like you are speaking about childComponents noDataRow: see how it works in this demo https://komarovalexander.github.io/ka-table/#/search just enter some random text to search field

**Comment by olliejm** [comment]
Ah thank you I missed that completely, makes sense
