### ISSUE TITLE
Virtual Scroll not working when pagination is set

### ISSUE THREAD

**Issue by gopalkcts** [komarovalexander/ka-table#227]
Hi Alex
  When I set the below config for the table

 const tablePropsInit: ITableProps = {
  columns: columnsArray,
  data: data.queryResponse.dataRecords,
  rowKeyField: 'id',
  virtualScrolling: {
    enabled: true
  },
  filteringMode:FilteringMode.FilterRow,
  sortingMode:SortingMode.Single,
  selectedRows:[0],
  columnResizing: true,
  width:3000,
  paging: {
    enabled: true
  },
};

I see virtual scrolling is not working. Could you please check?

**Comment by komarovalexander** [comment]
Hi @gopalkcts this is because you did not set page size property 
```
paging: {
  enabled: true,
  **pageSize: 100**
},
```
by default, pageSize is 10 so there is not enough data to do virtual scrolling, probably all of them are shown on one page without scrolling
