### ISSUE TITLE
How to identify the selected rows on a table?

### ISSUE THREAD

**Issue by gopalkcts** [komarovalexander/ka-table#228]
Hi Alex
  When we select all the rows or few rows by click on the checkbox,Is there a way to find out the number of rows selected and their row details? 

Thanks
Gopal

**Comment by komarovalexander** [comment]
selection demo: https://komarovalexander.github.io/ka-table/#/selection

yes, all selected ids are stored in `selectedRows` property of the table, it is an array so you can easily know length of it. And to get additional data about selected row you have to search by data array (or another datasource)

**Comment by LavaRiddle** [comment]
Hi Alex!

Is it possible to do:

```
useEffect(() => {
   // do something with the selected row Id's
}, [table.props.selectedRows])
```

I've been testing it out on a branch, the props don't seem to trigger the useEffect

**Comment by komarovalexander** [comment]
Hi @LavaRiddle why do you need that? you can subscribe to onDispatch and do something for SelectSingleRow action only: https://stackblitz.com/edit/table-selection-single-ts-yzvpdm?file=Demo.tsx

**Comment by xamogh** [comment]
@komarovalexander hey is there a way we can get selectedRows ? The selectedRows property cannot be accessed outside the table? Here is a example of what im trying to achieve:
https://stackblitz.com/edit/table-selection-ts-tcexdj?file=Demo.tsx

**Comment by komarovalexander** [comment]
@xamogh there are two ways how to do that.
Please check demos:
1. https://komarovalexander.github.io/ka-table/#/selection-single
2. https://komarovalexander.github.io/ka-table/#/selection
