### ISSUE TITLE
In all the examples, you used a static list of columns. Can you tell me what I need to do to load the columns dynamically? 

### ISSUE THREAD

**Issue by komarovalexander** [komarovalexander/ka-table#230]
_Originally posted by @ZenWhite in https://github.com/komarovalexander/ka-table/issues/213#issuecomment-1222505828_

Since it's not quite clear to me how to tie this in with the dispatch:
In all the examples, you used a static list of columns. Can you tell me what I need to do to load the columns dynamically? Since it's not quite clear to me how to tie this in with the dispatch:
![image](https://user-images.githubusercontent.com/44776755/185956609-c9126a6c-6a2f-430f-8f1b-6ab12356ea6b.png)
My data is displayed, but at the same time there is a strange empty space:
![image](https://user-images.githubusercontent.com/44776755/185957245-39504753-b046-4a4b-a425-f794a6cdf7cc.png)

**Comment by komarovalexander** [comment]
Hi @ZenWhite 

> My data is displayed, but at the same time there is a strange empty space:

can you try to use just `virtualScrolling: { enabled: true }` without height settings?

**Comment by komarovalexander** [comment]
> In all the examples, you used a static list of columns. Can you tell me what I need to do to load the columns dynamically? Since it's not quite clear to me how to tie this in with the dispatch:

do you need action to add a column? like `dispatch(addColumn(column))` - at this time table do not have that but I can add it later if necessary, or you just can do `tableProps.columns.push(column)`

**Comment by komarovalexander** [comment]
can you move those settings to tableProps: 
![image](https://user-images.githubusercontent.com/17903747/185964571-d59e02f0-523d-4def-9ed2-5cdf4e73f130.png)

otherwise kaReducer will not change them, this also could be the reason why virtual scrolling does not work

**Comment by komarovalexander** [comment]
like
```
const [tableProps, changeTableProps] = useState({
data: lessonStore.list,
rowKeyField: 'id',
columns:cols,
virtualScrolling: {enabled: true }
....
});
```

**Comment by ZenWhite** [comment]
I moved the data and it updates. But the empty space still exists:

![image](https://user-images.githubusercontent.com/44776755/185966493-61396e7a-c82a-43eb-a303-70696dee8776.png)
![image](https://user-images.githubusercontent.com/44776755/185966853-f5dbde6b-829a-44e7-9740-be3dde7d6106.png)
![image](https://user-images.githubusercontent.com/44776755/185966161-5b687769-5e55-488a-8a49-78c60934cb8d.png)

[object Object Object] -- my future card components

**Comment by komarovalexander** [comment]
can you reproduce it on stackblitz?  https://stackblitz.com/edit/table-overview-ts-nvy25w?file=Demo.tsx
