### ISSUE TITLE
support insert new col at index

### ISSUE THREAD

**Issue by chenshy39** [komarovalexander/ka-table#233]

**Comment by komarovalexander** [comment]
Hi `ka-table` is easy to customize so you can create your custom action and reducer for this purpose: https://stackblitz.com/edit/table-overview-ts-5bkbvw?file=Demo.tsx

but it is common case, I will keep this issue opened and will close it when build-in action creator will be there

**Comment by komarovalexander** [comment]
HI @chenshy39 in v7.14.0 `insertColumn` action has been added
