### ISSUE TITLE
Accessing current row count on grouped and filterable table

### ISSUE THREAD

**Issue by ceessay** [komarovalexander/ka-table#237]
Hi thanks very much for the work. This library is hands down the best table library out there.
My colleagues and I are in awe and grateful for the thoughtfulness.

We have a use case where we have a grouped and filterable (header filter) tables. 

Is there is a way to access the updated row count of each group when filtering changes ?  We need to display that row count

My apologies if the is not the place to post question. Please, if needed, kindly redirect me to the questions page

**Comment by komarovalexander** [comment]
Hi @ceessay do you need to show that length in grouping summary: https://komarovalexander.github.io/ka-table/#/grouping-summary ?
there is a demo how to do that for filtered values: https://stackblitz.com/edit/table-grouping-summary-ts-khj3mx?file=Demo.tsx

**Comment by ceessay** [comment]
No int the grouping header instead like in the capture below
![image](https://user-images.githubusercontent.com/15385670/189960288-f6a345eb-642b-40ff-bb45-cb5aeaa511c6.png)

**Comment by komarovalexander** [comment]
Unfortunately, the group data is not available in the current version of the component, I will add it out of the box in the next versions.
At this time you can use this workaround: https://stackblitz.com/edit/table-grouping-summary-ts-mzq1zw?file=Demo.tsx

**Comment by ceessay** [comment]
This is exactly what I needed! Thanks for the help

**Comment by komarovalexander** [comment]
Closing for now as there is a workaround. Will wait for further requests to make it out of the box
