### ISSUE TITLE
Action on individual row render

### ISSUE THREAD

**Issue by hope-portal-services** [komarovalexander/ka-table#239]
This may be a specific need unique to me, but I could see it being a useful hook to include.

I suppose creating your own dataRow component could accomplish something similar, but a more straightforward approach would be to have a `beforeRender` hook for rows. This functionality could extend to cells or columns, but specifically to be able to fire a function on each row render would be a useful feature.

**Comment by komarovalexander** [comment]
Hi @hope-portal-services for what purpose do you need it? 
You can use content property in child component and do not return anything 
demo: https://stackblitz.com/edit/table-overview-ts-unpvtj?file=Demo.tsx 
It executes before every render and in case nothing is returned renders the default row
