### ISSUE TITLE
Multiple Client Side Sort

### ISSUE THREAD

**Issue by mmartinsky** [komarovalexander/ka-table#241]
I think it would be useful to have a Multiple / MultipleTripleState sort that does not require remote - are there any challenges to implementation you have already encountered?

**Comment by komarovalexander** [comment]
starting from 7.13.0 it is possible using `extendedSort` option and any other custom sort library 
demo: https://komarovalexander.github.io/ka-table/#/sorting-extended 
(do not forget to set sortingMode={SortingMode.MultipleTripleStateRemote} to disable ka-table built-in local sorting)
