### ISSUE TITLE
Virtual scrolling breaks when showing new row

### ISSUE THREAD

**Issue by barucAlmaguer** [komarovalexander/ka-table#242]
Hi, I just found an issue when triggering the "show new row" action on a virtualized table.

You can easily reproduce the case with the default virtualized example from ka-table docs:

[TS Example](https://stackblitz.com/edit/table-many-rows-ts?file=Demo.tsx)

And triggering the action like this in the body of the Component:

```typescript
// ADD THIS:
import { showNewRow } from 'ka-table/actionCreators'

const ManyRowsDemo: React.FC = () => {
  const [tableProps, changeTableProps] = useState(tablePropsInit);
  const dispatch: DispatchFunc = (action) => {
    changeTableProps((prevState: ITableProps) => kaReducer(prevState, action));
  };
  
  // ADD THIS:
  useEffect(() => {
    dispatch(showNewRow())
  }, [])

  return (
    <>
      <Table
        {...tableProps}
        dispatch={dispatch}
      />
    </>
  );
};

```

result:

<img width="864" alt="Screen Shot 2022-09-23 at 18 04 51" src="https://user-images.githubusercontent.com/16729556/192067737-48143286-4f7b-4d93-a4a2-29ab0225294f.png">

I think the problem is that the virtualization code doesn't take into account that a "create new row" may be as the top row, and it should subtract it's height to the total "virtual row" it puts on top

**Comment by komarovalexander** [comment]
Hi, @barucAlmaguer thank you! I have reproduced that and will fix it this week

**Comment by komarovalexander** [comment]
the issue was fixed in `7.6.2` version
demo https://stackblitz.com/edit/table-many-rows-ts-akyv2v?file=Demo.tsx

**Comment by barucAlmaguer** [comment]
Thanks!
I'll check it out 😄

**Comment by dcantu96** [comment]
@komarovalexander hi there, I'm helping @barucAlmaguer test this bug fix we stumbled upon a funny type error.

```
error TS2551: Property 'UpdateTreeGroupsExpanded ' does not exist on type 'Partial<Record<"ClearFocused" | "ClearSingleAction" | "CloseEditor" | "CloseRowEditors" | "DeleteRow" | "DeselectAllFilteredRows" | "DeselectAllRows" | "DeselectAllVisibleRows" | "DeselectRow" | ... 49 more ... | "Validate", (currentProps: ITableAllProps, params?: any) => void>>'. Did you mean 'UpdateTreeGroupsExpanded'?
```

The `ActionType` enum type has a `UpdateTreeGroupsExpanded` with the value being `"UpdateTreeGroupsExpanded "` with an empty space at the end.
![Screen Shot 2022-10-03 at 16 37 32](https://user-images.githubusercontent.com/32658690/193689719-981df4fc-a627-4208-b050-45f3e3af8c97.png)

Should I create a separate issue for this?
