### ISSUE TITLE
Sorting doesn't work if custom header component

### ISSUE THREAD

**Issue by aleksei-baryshnikov** [komarovalexander/ka-table#246]
If using a custom header cell component then it won't work.

Example:
https://stackblitz.com/edit/table-custom-header-cell-ts-a3crzg?file=Demo.tsx

**Comment by komarovalexander** [comment]
Hi @aleksei-baryshnikov 
`headCell` overrides the whole component and its behavior
you have 2 ways to make it work:
1) use `headCellContent` https://stackblitz.com/edit/table-custom-header-cell-ts-vkmq6n?file=Demo.tsx
OR
2) add onclick and dispatch required action: https://stackblitz.com/edit/table-custom-header-cell-ts-xfhmuf?file=Demo.tsx

best regards
