### ISSUE TITLE
Custom Header Filter, need advise

### ISSUE THREAD

**Issue by arutsh** [komarovalexander/ka-table#248]
Hello, 

I am trying to make a custom header filter. 
I have following code 
`ldComponents={{
            headFilterButton: {
              content: (props) => {
                switch (props.column.key){
                  case 'name': return <></>;
                  case 'price': return <NumberEditor {...props}/>;
                }
              }`

When I try it shows both elements mine and default one. please see attached gif

can you please advise if it is possible to rewrite default functionality.... and if yes how it has to be done?

![headerFilter](https://user-images.githubusercontent.com/16839194/196473099-ea8a371b-2dc7-4e18-b36e-cfcb21304326.gif)

p.s. I know about rowfilter but I would prefer to have header filter since it does not add additional row for filter.

thanks 
Noro

**Comment by komarovalexander** [comment]
Hi @arutsh 
I think you can do something like this:
https://stackblitz.com/edit/table-header-filter-ts-4yxuvs?file=Demo.tsx
in this demo `childComponents.popupContent` is used to override popup content
```
 popupContent: {
          content: ({ column, childComponents, dispatch }) => (
            <FilterRowDataType
              key={column.key}
              column={column}
              childComponents={childComponents}
              dispatch={dispatch}
            />
          ),
        },
```
and FilterRowDataType is the component which is used by filterRow. So basically you can place filterRow cell into header filter popup

cheers!

**Comment by arutsh** [comment]
Thanks Alex,
exactly what I was looking for. Works like charm
