### ISSUE TITLE
rowReordering use case

### ISSUE THREAD

**Issue by hope-portal-services** [komarovalexander/ka-table#253]
While `rowReordering` is a neat feature, how is it utilized aside from visually reordering whats currently on the screen?

You can harness `onDrag` and `onDrop` on a `dataRow` childComponent - But this doesn't really accomplish much.

OnDrag, if you were to pull the dataRow's rowData, its the current row
OnDrop, if you were to pull the dataRow's rowData, its whichever row the dragged row was dropped onto.

Great.

Indexes aren't updating though across the entire table, so how would you end up with a concise row order after a `Drop` event?

Access to the dragged and dropped rowKeyValues is a possibility, but that does not account for the other X amount of rows in the table which are now displaced by the move, ie: every row below the dropped row now needs to have their index updated by -1, etc.. etc..

Is there any handling of this baked into ka-table? Or is the feature just for visual purposes. `columnReordering` is a great visual feature. `rowReordering` has much more utility, thus you would want to have an updated indexing of the table after the drag and drop events.

**Comment by komarovalexander** [comment]
Hi, I did not get your question. Here is a demo that shows that actual index is also changed: https://stackblitz.com/edit/table-row-reordering-ts-nehztu?file=Demo.tsx

**Comment by hope-portal-services** [comment]
Hi @komarovalexander, thanks for your response. I don't know how I missed this, but this demo explains it perfectly. Thanks!
