### ISSUE TITLE
Allowing users to group by columns

### ISSUE THREAD

**Issue by zatopek-firstis** [komarovalexander/ka-table#255]
Greetings, I would like to discuss possibility of users defining by what column they want to group by. 

Right now, I have found in your documentation and examples that it can be done only during initialization of tableProps, or by setting groups directly through setTableProps.

What I have in mind is, on Table would be some boolean like "allowUserGrouping", where if it is true, there would be some row above Table, where users can drag columns.

Here is example:
![table-user-grouping](https://user-images.githubusercontent.com/72503723/199708675-868be556-dd5e-4239-88c1-2422a440f1a5.png)
![table-user-grouping_grouped](https://user-images.githubusercontent.com/72503723/199708683-e959a960-e569-4211-8e9a-0073fafa890e.png)

Would it be possible to implement it natively please?

**Comment by komarovalexander** [comment]
Hi thanks for your request, This is feature which would be useful in ka-table, but there are no plans to implement that till the end of the year. I will keep this issue opened and will let you know if any updates

**Comment by komarovalexander** [comment]
Hi @zatopek-firstis you have to implement that using childComponents, custom reducer and drag and prop events. I think I will not be able to implement that out of the box this spring

**Comment by komarovalexander** [comment]
Hi @zatopek-firstis I think I can add some helper methods and create an example how to use them to implement that. I will do it later today

**Comment by zatopek-firstis** [comment]
Thanks @komarovalexander but that is not necessary. We already have that functionality on our former grid that we created. I will just adjust that to fit into your KaTable and our wrapper.

This issue was more about out-of-the-box general functionality. Thanks anyway.

**Comment by komarovalexander** [comment]
@zatopek-firstis let me investigate it today, I will let you know maybe I can implement it this week

**Comment by komarovalexander** [comment]
@zatopek-firstis I will release first version of that this weekend

**Comment by komarovalexander** [comment]
released in v7.14.0
