### ISSUE TITLE
Expand button on second column in tree view

### ISSUE THREAD

**Issue by zatopek-firstis** [komarovalexander/ka-table#262]
Greetings,

we want to have first column with some commands behavior, and without spacing, as shown on the image below.

![image_2022_12_19T13_10_33_551Z](https://user-images.githubusercontent.com/72503723/210325574-a50dc516-fb92-4f2b-8d1f-ba0b089defb4.png)

The problem is expand button is always on first column, no matter what. Because of that behaviour, the command buttons are always after the spacing and not nicely below themself.

Would it be possible to specify which column index should have tree expand buttons please?

**Comment by komarovalexander** [comment]
Hi @zatopek-firstis I've just added `treeExpandButtonColumnKey` in `7.7.0`

check this demo https://stackblitz.com/edit/table-tree-mode-ts-11erwt?file=Demo.tsx

release https://github.com/komarovalexander/ka-table/releases/tag/7.7.0
