### ISSUE TITLE
Scroll jumping when Row details + Virtualization are enabled

### ISSUE THREAD

**Issue by Drmwkz** [komarovalexander/ka-table#266]
Demo: https://stackblitz.com/edit/table-details-row-ts-egm4vp?file=Demo.tsx

When Virtualization is enabled and row level details are expanded, if you scroll past an expanded row, it hides the expanded row (Row and row details) prematurely, resulting in a visible jump of the table. This appears to be as the virtualization is not accounting for the Row details row's height.

**Comment by komarovalexander** [comment]
Hi @Drmwkz 
if you have fixed size of rows, here is a workaround how you can fix that: https://stackblitz.com/edit/table-details-row-ts-uvlctj?file=Demo.tsx

see this line
```
      virtualScrolling={{
        ...option.virtualScrolling,
        itemHeight: (data) => {
          if (option.detailsRows.includes(data.id)) {
            return 295;
          }
          return 45;
        },
      }}
```

let me know if it works for you, thanks!

**Comment by Drmwkz** [comment]
That unblocks us, thank you!
Just out of curiosity since we do have variable height rows, any plans to address this in the future?

**Comment by komarovalexander** [comment]
@Drmwkz sure, I will keep the issue opened and will let you know if any update
