### ISSUE TITLE
can we have row grouping with multiple nesting levels in material react table?

### ISSUE THREAD

**Issue by SRGajjala** [komarovalexander/ka-table#267]

**Comment by komarovalexander** [comment]
Hi @SRGajjala yes you can, can you share the stackblitz example what the issue is?

**Comment by SRGajjala** [comment]
I have not started on it yet, please share some sample code as there is no
documentation on it.

**Comment by komarovalexander** [comment]
https://komarovalexander.github.io/ka-table/#/grouping
