### ISSUE TITLE
Validation based on different column when adding new row

### ISSUE THREAD

**Issue by TineFr** [komarovalexander/ka-table#274]
Hello @komarovalexander

For a table with the columns 'lowerLimit' and 'upperLimit', I would like to implement a validation that checks whether
the value in the upperLimit column is not smaller or equal to the value in the lowerLimit column.
I have the following validation:

![image](https://user-images.githubusercontent.com/92461905/214097200-28dd7383-7715-4be9-9bb2-cf053e4d3da2.png)

This works fine when editing an existing row, but when adding a new row, rowData is undefined. 
Is there any way to implement this validation?

**Comment by komarovalexander** [comment]
Hi @TineFr 
the issue has been fixed in 7.8.4

demo:
https://stackblitz.com/edit/table-add-row-ts-kqjkze?file=Demo.tsx

**Comment by TineFr** [comment]
Thank you for your quick response @komarovalexander !
