### ISSUE TITLE
Datatype - Date - show 1 day previous date on selection.

### ISSUE THREAD

**Issue by chiragmewada** [komarovalexander/ka-table#279]
https://komarovalexander.github.io/ka-table/#/editing

Steps to reproduce
1) select date  from "next try" column using datepicker e.g feb 9 2023
2) when date selected it shows feb 8 2023

**Comment by komarovalexander** [comment]
Hi @chiragmewada thanks for that issue! Looks like this is because of timezone. Which timezone are you in?

**Comment by chiragmewada** [comment]
I am in EST

**Comment by chiragmewada** [comment]
Thank you :)

**Comment by komarovalexander** [comment]
fixed starting from version 7.8.5

**Comment by komarovalexander** [comment]
updated the demo on the site as well :)

**Comment by chiragmewada** [comment]
Thank you so much for this quick fix :) and thanks for this great table package.
