### ISSUE TITLE
Docs: Infinity Scroll demo not working

### ISSUE THREAD

**Issue by bay-jacewhitten** [komarovalexander/ka-table#295]
The demo is not loading. Also, 404 on svg images.

![Screen Shot 2023-03-14 at 7 37 12 AM](https://user-images.githubusercontent.com/79159096/225035469-e0631b1d-0640-4d78-803b-8ce96dd877d1.png)

**Comment by komarovalexander** [comment]
Hi @bay-jacewhitten what url are you opening? https://komarovalexander.github.io/ka-table/#/tree-mode ?

**Comment by bay-jacewhitten** [comment]
https://komarovalexander.github.io/ka-table/#/infinite-scrolling

**Comment by komarovalexander** [comment]
fixed, thanks
