### ISSUE TITLE
How To: How Do I Set Virtual Infinite Scroll To Max Page Height?

### ISSUE THREAD

**Issue by bay-jacewhitten** [komarovalexander/ka-table#296]
Hello, I would like to replicate this demo here => https://adazzle.github.io/react-data-grid/#/infinite-scrolling

Is there a way to achieve this with ka-table? I want to the full page height or the ability to have the page be the trigger to load more and have the page height grow.

Thanks!

**Comment by komarovalexander** [comment]
Hi @bay-jacewhitten you can set window.innerHeight as a container height demo: https://stackblitz.com/edit/table-infinite-scrolling-ts-lap9ep?file=Demo.tsx

**Comment by bay-jacewhitten** [comment]
Thanks, I will try this later this week and let you know if I run into any issues.
