### ISSUE TITLE
Rows flickering when scrolling the table

### ISSUE THREAD

**Issue by brunocryptohub** [komarovalexander/ka-table#302]
I'm experiencing the rows flickering when scrolling. I already checked the `virtualScrolling.itemHeight` and defined a `maxHeight` for the `tableWrapper`, also I memoized my data array and I'm sure there's no re-rendering issue. Everything looks good, what could cause this issue?

![ezgif-4-a831425e1a](https://user-images.githubusercontent.com/118673307/225771631-0e1e9128-d6e1-4ad8-aa52-fddcba24766d.gif)

**Comment by komarovalexander** [comment]
Hi @brunocryptohub try to memoize the data row like here https://komarovalexander.github.io/ka-table/#/many-rows-memo

**Comment by brunocryptohub** [comment]
@komarovalexander, the experience has improved, but I noticed that rows are re-rendered when scrolling. Can we preload additional rows above and below the visible area to improve the UX by having the next/previous rows ready in the DOM when scrolling?

**Comment by komarovalexander** [comment]
@brunocryptohub are you able to reproduce the issue on stackblitz https://stackblitz.com/edit/table-many-rows-memo-ts?file=Demo.tsx ?

**Comment by brunocryptohub** [comment]
@komarovalexander if I scroll very fast to the top, yes I can reproduce a few times. It is less noticeable because the cell texts are not heavy component or  compute anything.

**Comment by brunocryptohub** [comment]
@komarovalexander I'll aim to pre-render about 4 or 5 rows beyond the visible items, which will undoubtedly improve the user experience. The skeleton concept is also a great idea. Thank you for the fantastic package and your amazing contributions to our live!

**Comment by brunocryptohub** [comment]
@komarovalexander I'm reopening this issue because it appears to be highly relevant. I've noticed that virtualization libraries like react-window and react-virtualized include options for an "overscan" or "buffer" area surrounding the visible part of the list. Moreover, we should take into account that many use cases will require rendering actual components within the columns, instead of just simple HTML labels as shown in the examples.

Would it be possible to incorporate the overscan feature or perhaps provide a method for utilizing a custom virtualization component, such as react-virtualized or react-window, which offer this extremely crucial functionality?

**Comment by komarovalexander** [comment]
Hi, @brunocryptohub I do not have plan to change current behavior of virtualization. But table provides ability to override table body element (see child components) and do whatever you want with its children. I think you can try to wrap them in react virtualized or any other library you want to use

**Comment by brunocryptohub** [comment]
@komarovalexander It wasn't easy to integrate a different virtualization package; in fact, I abandoned that approach since it caused numerous issues and broke many styles. Instead, I modified the getVirtualized function and VirtualizedRows component to overscan additional rows, effectively preventing any rendering gaps. The result works incredibly well! If you're open to including this new feature, I'd be happy to submit a PR.

Thank you so much again!

https://user-images.githubusercontent.com/118673307/226181564-fd03acaf-ddfe-4f81-9fc3-f89823596537.mov

**Comment by komarovalexander** [comment]
@brunocryptohub this is great, open a pr please, I will check next week

**Comment by prabhjotkaur1087** [comment]
Hi, 

I had a similar issue going on within my application where I am using this table, could you please let me know what changes you made here to avoid the gaps? I am able to see gaps in the rows when I scroll from top to bottom and blank space is also there when I scroll from left to right, if  I have so many columns. Please suggest.

Thankyou.

**Comment by prabhjotkaur1087** [comment]
@komarovalexander please refer to this stackblitz example [here](https://stackblitz.com/edit/table-many-rows-ts-af3jeh9y?file=Demo.tsx,index.html)

I have added some more columns and rows, and also added the code to memorize the datarow.

If you try to scroll vertically to bottom, it will show white area, same is applicable in the horizontal scrolling.

Thanks.
