### ISSUE TITLE
Showing one custom component as row, and filter by another field (Assistance)

### ISSUE THREAD

**Issue by jspasiuk** [komarovalexander/ka-table#304]
Hi guys!! Excellent work, I love this table!!!

I just have a simple use case and cannot make it work. Is there any way to display a custom component, lets say something like

`<Text color="red">I am a component</Text>`

And then in the filter, show a different row (I want to filter for the raw element (I am a component).

I know there is a format option on the table, but I have every multiple tables with multiple components, and I wanted to use a simple table wrapper for all of them.

Any ideas would be great

Thanks a lot!!

**Comment by komarovalexander** [comment]
Hi @jspasiuk thanks! just FYI there is `childComponents` option for UI customization as well, but format is also good solution (it is up to you). 
as for "I have every multiple tables with multiple components," at this time you can have share format function and assign it to each table. But I also have plans to implement some default settings for all tables in one App. Will try to add it in further releases, thank you for your request!

**Comment by komarovalexander** [comment]
Hi @jspasiuk check custom cell demo https://komarovalexander.github.io/ka-table/#/custom-cell looks like it is your described case
