### ISSUE TITLE
Bug: z-index is never applied

### ISSUE THREAD

**Issue by bay-jacewhitten** [komarovalexander/ka-table#307]
Setting this on the column data, returns no results. This is in the latest release. Possible regression? 

Using the sticky columns option for my first two columns.

Tried with multiple ways.

![Screen Shot 2023-03-24 at 9 05 04 AM](https://user-images.githubusercontent.com/79159096/227579464-c8320c30-0b43-493f-af91-dbcee5824e02.png)
![Screen Shot 2023-03-24 at 9 15 00 AM](https://user-images.githubusercontent.com/79159096/227581874-c28df1d4-e72e-41da-b798-ede4db901cec.png)

Still no results.
![Screen Shot 2023-03-24 at 9 07 09 AM](https://user-images.githubusercontent.com/79159096/227579992-86ce8ab0-722a-430e-a98e-dc27eeeffae9.png)

This is conflicting with some elements that have position relative set inside of the cell

![Screen Shot 2023-03-24 at 9 13 39 AM](https://user-images.githubusercontent.com/79159096/227581541-f99902d3-d15d-4163-82d4-68fb971f7ab7.png)

**Comment by komarovalexander** [comment]
Hi @bay-jacewhitten can you reproduce it on stackblitz? https://stackblitz.com/edit/table-fixed-column-ts?file=style.scss

**Comment by bay-jacewhitten** [comment]
@komarovalexander Here you go => https://stackblitz.com/edit/table-fixed-column-ts-77uemy?file=Demo.tsx

zIndex as a string is never merged. ie: zIndex: '4 !important' , but as a number it is.

**Comment by komarovalexander** [comment]
Hi @bay-jacewhitten  '4 !important' will not work in inline styles in react https://stackoverflow.com/questions/23074748/important-inline-styles-in-react
why do you need !important in your case?
