### ISSUE TITLE
Table selection JS example bug

### ISSUE THREAD

**Issue by Snupas** [komarovalexander/ka-table#31]
Currently, the onchange event handler conditional for the checkbox input is set to:

` if (event.currentTarget.checked) {
          dispatch(ActionType.SelectRow, { rowKeyValue });
        } else {
          dispatch(ActionType.SelectRow, { rowKeyValue });
        }`
https://stackblitz.com/edit/table-selection-js?file=Demo.js

Should be like in the TS example:

`      
        if (event.currentTarget.checked) {
          dispatch(ActionType.SelectRow, { rowKeyValue });
        } else {
          dispatch(ActionType.DeselectRowData, { rowKeyValue });
        }
      `
https://stackblitz.com/edit/table-selection-ts?file=Demo.tsx

(Loving the component btw. Has just the right set amount of features built in to get going.)

**Comment by komarovalexander** [comment]
Hi @Snupas 
Thank you for your feedback, the issue was Fixed 
https://stackblitz.com/edit/table-selection-js?file=Demo.js
