### ISSUE TITLE
Header filter box floats out of view on Virtualized tables

### ISSUE THREAD

**Issue by Drmwkz** [komarovalexander/ka-table#313]
If you have a virtualized table with enabled header filters the filter popup goes out of view if you have scrolled down in the table.

Steps to repro:
- Create a table with virtualized rows enabled and header filters
- Open the filter popup on any column
- Start scrolling down (the popup should start scrolling until its out of view)

_Note: If you have scrolled down before opening the filter popup, the popup wont show (because its position is out of view already)_

Demo (To virtualized demo just added filterMode={FilteringMode.HeaderFilter}):
https://stackblitz.com/edit/table-many-rows-dynamic-ts-fuiac8?file=Demo.tsx

<img width="937" alt="image" src="https://user-images.githubusercontent.com/3238646/229862727-9314b9f9-ce00-4106-b0e9-36b9461e50db.png">

<img width="327" alt="image" src="https://user-images.githubusercontent.com/3238646/229863592-de5b1387-1e7d-4224-bbe5-0a5e3350eb60.png">

**Comment by komarovalexander** [comment]
fixed in v7.15.1
https://stackblitz.com/edit/table-many-rows-dynamic-ts-wgkqxv?file=Demo.tsx
