### ISSUE TITLE
the sort arrow icon appears at the bottom instead of on the side

### ISSUE THREAD

**Issue by GVALFER** [komarovalexander/ka-table#321]
Hi
Looks like there is a bug.
I copy and past you example, and when i click in the icon  sort arrow it shows at the bottom instead of on the side.

Using Tailwindcss as base.

![Image 2023-04-29 at 3 28 43 PM](https://user-images.githubusercontent.com/106562911/235308223-7aae2ba9-4896-4d75-b781-6d9f9f5e6253.jpeg)

**Comment by GVALFER** [comment]
this fixed:

.ka-thead-cell-content {
    width: 100%;
    display: flex; // added
    align-items: center; // added
}

**Comment by komarovalexander** [comment]
Hi @GVALFER can you reproduce it on https://stackblitz.com/edit/table-sorting-ts?file=Demo.tsx ?
