### ISSUE TITLE
ROW REORDERING WITHOUT CHANGING THE S/N 

### ISSUE THREAD

**Issue by jamilu-jibrilla** [komarovalexander/ka-table#329]
I have a table where i show the serial number of each row beside it. Is it possible to maintain the serial numbers while reordering the row here's an example:

```
s/n  column1   column2  column3    column4
------------------------------------------------
1.     cell           cell          cell        cell
------------------------------------------------
2.    cell2         cell2        cell2      cell2 
------------------------------------------------
```

is it possible to rearrange this rows while keeping the serial number constant?
Thanks.

**Comment by komarovalexander** [comment]
hi @jamilu-jibrilla you can do simple workaround, just check the example: https://stackblitz.com/edit/table-row-reordering-ts-xqee56?file=Demo.tsx

**Comment by jamilu-jibrilla** [comment]
Thanks a bunch......this is exactly what i was looking for.
