### ISSUE TITLE
Resizing column resizes more than one column

### ISSUE THREAD

**Issue by zatopek-firstis** [komarovalexander/ka-table#332]
Hello there

When resizing one column, programaticly it resizes that one column (as seen in element prospecting), but visualy more than one.

This is unexpected behavior, can you please take a look at it?

https://stackblitz.com/edit/table-column-resizing-ts-hgs8gv?file=Demo.tsx

**Comment by komarovalexander** [comment]
Hi @zatopek-firstis it is default behavior of html table.
the reason of that is that you have 4 columns with 200px width (800px in total), but table width is 1100px - what is bigger than all columns width. in this case table is doing column width change to fill the all free space, as a result when you change the width of one column it recalculates free space and changes the width of the column. Solution is to have columns width what fills all table width space in total 
https://stackblitz.com/edit/table-column-resizing-ts-dbhs9s?file=Demo.tsx

**Comment by zatopek-firstis** [comment]
Yes, you are right it is default behavior of table, but with set width of table and set width of columns it is only solved for initial state and with overresizing it "breaks". Our customers are unfortunately like that and it needs to be solved, so I guess I will be forced to do so.

In your demo, you just solved it for your amount of columns and width, but luckily I have huge monitor so I can show you how it behaves in my enviroment:

![columns1](https://github.com/komarovalexander/ka-table/assets/72503723/db5b038b-a50a-4839-bcb1-e00453360c8b)
![columns2](https://github.com/komarovalexander/ka-table/assets/72503723/54f9cf3b-1471-413c-bbe7-94c6a3c12964)

Like I said, the problem is that it programaticly changes the width of only one column:

![resize1](https://github.com/komarovalexander/ka-table/assets/72503723/b092fd17-c754-4330-82b2-9d45ce9ec26c)
![resize2](https://github.com/komarovalexander/ka-table/assets/72503723/d0711ddd-8529-4599-bfd9-783be6986c63)

The solution (and in my opinion the correct one), would be to change the width of both left and right column next to resizing point up to one of them has minimal width and then stop it.

Heres example what I have in mind:
https://demos.devexpress.com/MVCxGridViewDemos/Columns/ColumnResizing

Of course if you really do not want to do it and keep your behavior the same, which is understandable, let me know and me or one of my colleagues will have a look at it in our wrapper. If you would be interested in solution afterwards and maybe want to implement it, I think we will be open for it.

**Comment by komarovalexander** [comment]
@zatopek-firstis I will not customize the default behavior of html table for that case. As a solution you can have one buffer column without width and it will change it size https://stackblitz.com/edit/table-column-resizing-ts-hgs8gv?file=Demo.tsx

**Comment by komarovalexander** [comment]
btw there ae the easiest way to keep columns width: just remove min width from table https://stackblitz.com/edit/table-column-resizing-ts-kjhdaw?file=style.scss
