### ISSUE TITLE
Groups with groupedColumns

### ISSUE THREAD

**Issue by pm4r** [komarovalexander/ka-table#337]
When I try to use `groups` with `groupedColumns`, headers don't align well with columns - they are shifted to the left.
You can reproduce it by running code from https://komarovalexander.github.io/ka-table/#/grouping
And adding following to table props:
```js
groupedColumns= {[{
        key: 'groupedcolumn1',
        title: 'Group 1',
        columnsKeys: ['name', 'country']
}]}
```

**Comment by komarovalexander** [comment]
fixed in `v11.0.3`
thank to @zaycker
