### ISSUE TITLE
Formatted value

### ISSUE THREAD

**Issue by zatopek-firstis** [komarovalexander/ka-table#340]
Hi, I got an issue regarding formatting.

While processing in your core, all values get formatted by format function (tableState.format) and returns correct value. But then I have no means to access that formatted value in childComponents.cell or childComponents.cellText and I have to format it again to get the right display value. 
Can you please add formattedValue to cellText and cell?

**Comment by komarovalexander** [comment]
Hi @zatopek-firstis format is used by CellText, and formatted value is generated inside that component. You are doing it right way "I have to format it again to get the right display value" because you override cellText behavior and format is not called anymore by Table.
