### ISSUE TITLE
Resize column action ignores min-width on Firefox

### ISSUE THREAD

**Issue by krukrue** [komarovalexander/ka-table#370]
Hi, as was said in title, Firefox(+Safari) just ingores minimal width after resizing, we have option to hide it and set any size you want. 
My solution: make sure if new column width isn't more than minimal value a set minimal if it is (ActionType.ResizeColumn)

**Comment by komarovalexander** [comment]
Hi @krukrue can you give an example? I tried to reproduce that https://stackblitz.com/edit/table-column-resizing-ts-remrxe?file=Demo.tsx but it works in both Firefox and Safari

**Comment by komarovalexander** [comment]
I got that. `colGroup` minWidth does not work on firefox and safari. But you can set `style` for separate column to make it work as I did in example  https://stackblitz.com/edit/table-column-resizing-ts-remrxe?file=Demo.tsx
or as you said ResizeColumn is also a solution
