### ISSUE TITLE
Uncheck all is too slow when I have a lot of data

### ISSUE THREAD

**Issue by fshahmt** [komarovalexander/ka-table#371]
Apologies for creating a new issue. I understand you must be busy but I lost track of which issue I commented on

My issue is when I use the deselectAllFilteredRows, it just lags and sometimes just breaks the page. I tried with the demo too and as soon as I set Array(10000), it starts lagging. Is there a workaround because I work with a lot of data (often times over 10000) https://stackblitz.com/edit/table-selection-ts?file=Demo.tsx 

Please do let me know

**Comment by komarovalexander** [comment]
Hi @fshahmt you should not render 10000 rows in the dom, you have to use virtual scrolling https://komarovalexander.github.io/ka-table/#/many-rows or paging https://komarovalexander.github.io/ka-table/#/paging
