### ISSUE TITLE
Header Filter Popup Mispositioned with Horizontal Scrolling Table

### ISSUE THREAD

**Issue by sergeylin** [komarovalexander/ka-table#372]
Hi,

I found a problem with the header filter popup when using a table with horizontal scrolling. The popup shows up in the wrong spot, outside the table area. It seems like we can't control its position using the table props or other functions. 

<img width="735" alt="Screenshot 2024-01-17 at 9 16 01 PM" src="https://github.com/komarovalexander/ka-table/assets/85824310/09ce4cbb-fea1-4b03-b689-701b88aed4ea">

Can you help fix this?

Example of the bug:
https://stackblitz.com/edit/table-header-filter-ts-d7dwnl?file=Demo.tsx

Thanks.

**Comment by komarovalexander** [comment]
Hi @sergeylin thanks for provided example.

fixed in `v8.7.2` https://stackblitz.com/edit/table-header-filter-ts-gnoddg?file=Demo.tsx
