### ISSUE TITLE
Bulk select

### ISSUE THREAD

**Issue by aleksei-baryshnikov** [komarovalexander/ka-table#374]
Hello.
Is it possible to select a list of rows from the code?
I've seen `selectRowsRange` but not sure that it does fit my needs.
I would like to have somewhat like `selectRows([...rowIds])`.

**Comment by komarovalexander** [comment]
Hi @aleksei-baryshnikov starting from `v8.8.0` those guys are available:

```
selectRows(rowKeyValues)
deselectRows(rowKeyValues)
```

have a great weekend!
