### ISSUE TITLE
Is rows ordering  persistent?

### ISSUE THREAD

**Issue by aleksei-baryshnikov** [komarovalexander/ka-table#379]
Hi.

When I change a cell value the ordering of rows is not persistent.

E.g. I have that data set from a backend at the start with the ordering on the screen as in the dataset:
`[
  {
    id: 1,
    value: 1
  },
  {
    id: 2,
    value: 2
  },
  {
    id: 3,
    value: 3
  }
]`

I've updated cell with id = 2 and have this dataset form the backend:
`[
  {
    id: 1,
    value: 1
  },
  {
    id: 2,
    value: 10
  },
  {
    id: 3,
    value: 3
  }
]`
and now I have this oredering on the screen: `id:2, id:3, id:1`

I've tried to enable/disable default sort, disable sort at all - doesn't help.

Is that expected?

**Comment by komarovalexander** [comment]
Hi @aleksei-baryshnikov please provide an example on https://stackblitz.com/edit/table-sorting-ts?file=Demo.tsx , thanks
