### ISSUE TITLE
Column in ITableProps does not contain the property 'editor' 

### ISSUE THREAD

**Issue by cryptrr** [komarovalexander/ka-table#380]
From the docs.

```ts
const tableProps: ITableProps = {
  columns: [
    {
      dataType: DataType.String,
      editor: CustomLookupEditor,
      key: 'passed',
      title: 'Passed',
    }
  ],
};
```

`
Object literal may only specify known properties, and 'editor' does not exist in type 'Column'.
`

The example in the docs is not working.

I can do it with `cellEditor:{}` block inside ChildComponents. But the docs is confusing here.

**Comment by komarovalexander** [comment]
docs updated, thank you!
