### ISSUE TITLE
Filter operators isEmpty and isNotEmpty are Non-functional

### ISSUE THREAD

**Issue by krukrue** [komarovalexander/ka-table#384]
I prepared demo to show it:
https://stackblitz.com/edit/table-filter-row-custom-editor-ts-vpjndu?file=Demo.tsx

Tip for improving https://github.com/komarovalexander/ka-table/blob/master/src/lib/Utils/CommonUtils.ts - in isEmpty function would be good to compare not only null or empty array, but empty string also.

Thank you.

**Comment by komarovalexander** [comment]
Hi @krukrue thanks for example, I will investigate it. 
btw value.length === 0 is an empty string check also (maybe not obvious but it is covered by tests and do not see the reason to write (value.length === 0 || value =='') as both comparisons do the sane
