### ISSUE TITLE
Actual filtered data

### ISSUE THREAD

**Issue by aleksei-baryshnikov** [komarovalexander/ka-table#389]
Hello!
I struggle with that issue.
I need the actual filtered data. I know, that `kaPropsUtils.getData(props)` for this but if I have grouping and all groups are collapsed I am getting just groups or expanded data using this function.
Is here any way to get actual filtered data even if it is grouped and collapsed?

**Comment by komarovalexander** [comment]
Hi @aleksei-baryshnikov, just released `v8.9.0` with ability to do that.
demo: https://github.com/komarovalexander/ka-table/releases/tag/8.9.0
