### ISSUE TITLE
sort prop in ka-table not supporting server-side sorting

### ISSUE THREAD

**Issue by SupriyaK06** [komarovalexander/ka-table#391]
Hi Team,

I have been spending few hours figuring about sort prop in ka-table

As I read in few documentation sort prop in ka-table supports only client-side sorting?

I have been trying on sort prop-a handleSortChange function is triggered this function updates the sortfield and sortDirection state which in turn fetches the data from API
but on using this sort prop 1st on clicking the sortable column 1st client side sorting is happening followed but server side sorting
how can I disable the client side sorting and only enable sever side sort.

hoping for a quick response
Thank you

**Comment by komarovalexander** [comment]
Hi,there is singleRemote mode https://komarovalexander.github.io/ka-table/#/sorting-modes

**Comment by SupriyaK06** [comment]
hey,

thanks for the response
but if having the sorting mode as singleRemote then even the sort prop does not work?
because having the sorting mode as singleRemote its not even triggering the handleSortChange function which is associated with sort prop

hoping for a quick response
Thank you

**Comment by komarovalexander** [comment]
https://github.com/komarovalexander/ka-table/discussions/392
