### ISSUE TITLE
Jest deprecations on mock functions produced with jest.fn()

### ISSUE THREAD

**Issue by iqronfli** [komarovalexander/ka-table#407]
**change**:

- toBeCalled
- toBeCalledTimes
- toBeCalledWith

**with**:

- toHaveBeenCalled
- toHaveBeenCalledTimes
- toHaveBeenCalledWith

@komarovalexander if you want I can work on it :)

**Comment by komarovalexander** [comment]
Hi @iqronfli sure, thank you!
