### ISSUE TITLE
Unable to select all the cell content with mouse double click in firefox

### ISSUE THREAD

**Issue by fshahmt** [komarovalexander/ka-table#413]
For some reason I can use the double mouse click to select all the cell content in chrome but the same does not work in firefox and neither does clicking at the center of the cell. The cursor is just stuck at the end.

https://github.com/komarovalexander/ka-table/assets/101728655/0b24c7d3-e4d5-4d36-ab40-7af2dd0f6ce7

I have attached two videos, the one in 

https://github.com/komarovalexander/ka-table/assets/101728655/a678863f-58a7-4d53-8fb4-f315333a01cb

which the double click works in google chrome and the one in which it does not is firefox. I can't seem to figure out what is causing this to happen.

**Comment by komarovalexander** [comment]
Hi @fshahmt I cant reproduce it on this demo on firefox https://komarovalexander.github.io/ka-table/#/editing, could you provide stackblitz example? https://stackblitz.com/edit/table-editing-ts?file=Demo.tsx

By default table uses native browser editors

**Comment by fshahmt** [comment]
> Hi @fshahmt I cant reproduce it on this demo on firefox https://komarovalexander.github.io/ka-table/#/editing, could you provide stackblitz example? https://stackblitz.com/edit/table-editing-ts?file=Demo.tsx
> 
> By default table uses native browser editors

Thank you sooo much for such a quick response. I'll try and replicate it on stackblitz if possible. Could you in the meantime help me out. I want to be able to manipulate the input (the native browser editor) but can't seem to figure out how I can go about it in ka-table

**Comment by komarovalexander** [comment]
You can access it using childComponents.cellEditorInput https://ka-table.com/docs_props.html#childcomponents

**Comment by fshahmt** [comment]
Apologies for not responding yesterday and again thank you so much for the prompt response. I have now found a workaround. The previous team seems to have screwed the codebase so much that even the features that you provide by default don't work unless I try workarounds. You were really helpful and thank you again for being so quick in the support.
