### ISSUE TITLE
Feature Request: When virtualScroll is enabled, have Summary row always be visible

### ISSUE THREAD

**Issue by JeanCGF** [komarovalexander/ka-table#418]
I know this isnt a small change, but a feature that it's missing and I would like to have is being able to keep the summary row to always be visible in case `virtualScrolling` is true, in the same way that the headers are fixed in place when scrolling.

**Comment by komarovalexander** [comment]
Hi @JeanCGF 
it is actually not a problem just add
```
          elementAttributes: () => ({
            style: {
              position: 'sticky',
              bottom: 0,
              backgroundColor: 'white',
            },
          }),
```
to `childComponents.summaryCell`

demo https://stackblitz.com/edit/table-many-rows-ts-jdzfpv?file=Demo.tsx
