### ISSUE TITLE
Typo and missing default flags in static/themes/default.scss

### ISSUE THREAD

**Issue by CplShepherdFIT** [komarovalexander/ka-table#422]
Typo `$ka-selecter-background-color`,
`$ka-paging-pages-margin` and `$ka-paging-pages-padding` missing `!default` flag.
(And I hope that's it)

![image](https://github.com/komarovalexander/ka-table/assets/93290008/dc582b21-bbd6-410b-a63e-444b33c3b1ba)

**Comment by komarovalexander** [comment]
Hi @CplShepherdFIT feel free to create pr, I will approve that later

**Comment by komarovalexander** [comment]
defaults ave been fixed in `v11.0.2`
