### ISSUE TITLE
Display both up and down arrows for non sorted column

### ISSUE THREAD

**Issue by dyaacov** [komarovalexander/ka-table#427]
Hi,

When my columns are not sorted, I would like to add both arrows so users can see that this column is sortable.
is it possible?

I've found an example how to control the sortIcon but this event is invoked only AFTER I click a cell.

https://komarovalexander.github.io/ka-table/#/sorting

Thanks!

**Comment by dyaacov** [comment]
OK found an example how to control the sortIcon

https://komarovalexander.github.io/ka-table/#/sorting

**Comment by komarovalexander** [comment]
hi @dyaacov you can show it in `headCellContent`, see the demo https://stackblitz.com/edit/table-sorting-ts-tseedw?file=Demo.tsx

**Comment by dyaacov** [comment]
Yep!
Found it a minute ago :)

Thanks!
