### ISSUE TITLE
Alternate row background in virtualize mode

### ISSUE THREAD

**Issue by dyaacov** [komarovalexander/ka-table#428]
Hi All,

I'm trying to set different background color for even rows.
In virtualize, while scrolling, even and odd are changing all the time.

Is there another solution to overcome this situation?

Thanks!

**Comment by komarovalexander** [comment]
Hi @dyaacov  there is an ability to do that using `childComponents.dataRow`
demo: https://stackblitz.com/edit/table-many-rows-ts-bmfyda?file=Demo.tsx,style.scss,index.tsx

but I will keep this issue open, will wait further requests. It looks like a candidate to implement out-of-the-box

**Comment by komarovalexander** [comment]
Hi @dyaacov `oddEvenRows` property has been added in `11.1.0`: https://github.com/komarovalexander/ka-table/releases/tag/11.1.0
