### ISSUE TITLE
Data not showing while using useEffect with state

### ISSUE THREAD

**Issue by udayan-santu** [komarovalexander/ka-table#429]
> useEffect(() => {
>         if(dataColumn !== null) {
>             return table.changeProps({columns: dataColumn.map((column) => {
>                     if(column.type === 'text') {
>                         return { key: column.id, title: column.name, dataType: DataType.String, visible: column.visibility, sticky: column.sticky }
>                     } else if(column.type === 'image') {
>                         return { key: column.id, title: column.name, dataType: DataType.String, visible: column.visibility, sticky: column.sticky }
>                     } else {
>                         return { key: column.id, title: column.name, dataType: DataType.String, visible: column.visibility, sticky: column.sticky }
>                     }
>                 })
>             });
>         }
>     }, [dataColumn]);

When I am using useEffect with [], the data are showing. but with a state -> dataColumn it going invisible data. Even noData props also not working.

**Comment by komarovalexander** [comment]
Hi @udayan-santu please provide stackblitz example https://stackblitz.com/edit/table-overview-ts?file=Demo.tsx

**Comment by udayan-santu** [comment]
> Hi @udayan-santu please provide stackblitz example https://stackblitz.com/edit/table-overview-ts?file=Demo.tsx

Hi.. Thanks for your reply. Please check [Stackblitz here](https://stackblitz.com/edit/table-overview-ts-krvuln?file=Demo.tsx)

**Comment by udayan-santu** [comment]
I solved the problem, using, 2 more props, rowKeyField and data.
Thank you
