### ISSUE TITLE
Cannot change pageIndex through useState

### ISSUE THREAD

**Issue by CplShepherdFIT** [komarovalexander/ka-table#431]
I'm trying to save pageIndex to session storage, so I have a useState `[pageIndex, setPageIndex]`. Next, I have

```
const table = useTable(...
onDispatch:
if (action.type === ActionType.UpdatePageIndex) {
    setPageIndex(action.pageIndex);
}
```
and
```
<Table
table={table}
paging={{
    pageIndex: pageIndex,
    enabled: true,
    pageSize: 10,
    position: PagingPosition.Bottom,
}}
```

With this setup the pageIndex gets reset to 0 every time I reload the page. I have tried all sorts of different solutions, one has worked for one refresh, the other seems to switch the paging for a second and then switch back and so on.

**Comment by komarovalexander** [comment]
Hi @CplShepherdFIT looks like instead of `useState` you have to store data in `sessionStorage`. (example with localStorage https://komarovalexander.github.io/ka-table/#/state-storing).
If you need help, please provide an example on stackblitz https://stackblitz.com/edit/table-state-storing-ts?file=Demo.tsx what you are trying to achieve

**Comment by CplShepherdFIT** [comment]
I have a `useEffect` that upon change of `pageIndex` saves the new options to session storage, so the demo was not really applicable. Nevertheless I have solved the problem by doing this (based on the demo):

```
onDispatch: async (action, newProps) => {
            if (newProps.paging && newProps.paging.pageIndex) {
                setPageIndex(newProps.paging.pageIndex);
            }
```
instead of checking the `action` itself. This is very much acceptable for now. Thanks for the help.

**Comment by CplShepherdFIT** [comment]
Ah nevermind it doesn't work with `0` now..

**Comment by CplShepherdFIT** [comment]
Is there any reason why the `UpdatePageIndex` action is triggered when the component initially renders?
![image](https://github.com/user-attachments/assets/d0ed5d80-e0d3-4d5a-a0b0-486e614bbc48)

**Comment by komarovalexander** [comment]
can you reproduce that on https://stackblitz.com/edit/table-paging-ts?file=Demo.tsx ?
