### ISSUE TITLE
question: how can we override a row's height to a smaller size?

### ISSUE THREAD

**Issue by diogoparente** [komarovalexander/ka-table#440]
Hey @komarovalexander 👋 

I see that ka-table is forcing a [default cell height](https://github.com/komarovalexander/ka-table/blob/f662f8368f80144e6d9026aa1dbf41da82edea78/src/lib/static/themes/default.scss#L40), which I can only override by setting the value to a bigger value, otherwise it does not apply whatsoever.

Is there a way to do so?

I've already tried to define a custom override.scss and try to assign a different value to `$ka-header-cell-height`, but it still didn't work.

Shouldn't we be able to specify a `<tr>` and `<thead/>` height through props?

Thank you for such a flexible OSS table!

**Comment by komarovalexander** [comment]
Hi @diogoparente looks like you need to override paddings as well ($ka-thead-cell-padding)
demo: https://stackblitz.com/edit/table-custom-theme-ts-ur2pni?file=dark.scss

> Shouldn't we be able to specify a <tr> and <thead/> height through props?
you can do it by childComponents, but I would recommend to override default styles in scss

**Comment by diogoparente** [comment]
Thanks for the quick help, @komarovalexander!

Your example works really well, but unfortunately, we are wrapping ka-table in a styled-components container to target specific sections, so we can’t go down that route.

The closest solution I can think of is creating multiple .scss files with the specific variant rules, then having an override.scss file with classes that apply those rules and conditionally choose the correct class.

This would require us to adjust our approach to styling, which may lead to changes in the design requirements rather than the styling method.

I appreciate your time and help! 🙇‍♂️
