### ISSUE TITLE
 Disable draggable using some prop in column.

### ISSUE THREAD

**Issue by krukrue** [komarovalexander/ka-table#442]
I have a problem in my project, I want to keep some columns nonDraggable, but I have to use pointer-events: none, which will block all my other functions, like sorting, filtering. I have no direct access to change drag property. Can you please make some new property inside of KaColumn, where we can set property that we don't want have it draggable at all, but only this column. Now columnReordering turns it on everywhere.

I found it here:
https://github.com/komarovalexander/ka-table/blob/e462d7202b4a782c142a8983cabb22cbbe51a016/src/lib/Components/HeadCell/HeadCell.tsx

**Comment by komarovalexander** [comment]
@krukrue use `v11.2.0` it does have it now
thank for the request

BR
Alexander
