### ISSUE TITLE
Why does no children equal to treeDeep + 1 ? 

### ISSUE THREAD

**Issue by hurnik-firstis** [komarovalexander/ka-table#448]
Hey, 

I'm currently experiencing a bug with the tree structuring and I wanted to ask.

In the file TreeUtils.ts you're declaring a constant getItemsStructure on line 13 and I dont understand why does !children return to treeDeep + 1 and when there are children it returns to regular treeDeep with a forEach that adds the + 1 anyway.

Could you please explain ? 

Thank you.

**Comment by komarovalexander** [comment]
Hi @hurnik-firstis can you reproduce a bug you faced on stackblitz? https://stackblitz.com/edit/table-tree-mode-ts?file=Demo.tsx 

`getItemStructure` is recursive function, and in case of children exist it is called again for each child and `treeDeep` parameter for it increased on 1. So it will return at least `treeDeep + 1 + 1` for a child, or maybe deeper value in case there are children in child. I don't see a bug here yet
sorry for this recursive function is not so obvious

thanks for the question

**Comment by hurnik-firstis** [comment]
Hey, thanks for your response, I just commented out the children from the data array.

Once there are no children and the property treeGroupKeyField={'treeGroupId'} not undefined it auto inputs a class ka-tree-empty-cell (treeDeep + 1) and there's no way for me to control it otherwise than setting treeGroupKeyField to undefined or deleting it in general.

The behaviour what I expect is that when there are no children and treeGroupKeyField is not undefined there's no need for an empty tree cell up until the table has to make space for the treeArrowElement.


 https://stackblitz.com/edit/table-tree-mode-ts-8zgfw2?file=Demo.tsx

**Comment by komarovalexander** [comment]
@hurnik-firstis I think fix for you will be not set treeGroupKeyField in case of treeGroupId is undefined:
```
 treeGroupKeyField={
        data?.some((x) => x.treeGroupId) ? 'treeGroupId' : undefined
      }
```
this way table will not add free space, otherway it expects tree data to have children

demo: https://stackblitz.com/edit/table-tree-mode-ts-ennu4o?file=Demo.tsx

**Comment by hurnik-firstis** [comment]
@komarovalexander yeah this makes sense, still a workaround but i guess it has to make do.

Thank you !
