### ISSUE TITLE
Virtual Scrolling and Dynamic height parent / page element

### ISSUE THREAD

**Issue by bay-jacewhitten** [komarovalexander/ka-table#456]
Hello,

More of a question or enhancement, but is there a way to use the virtual scrolling with a dynamically set height? I see in the code example a max height is set on the table wrapper. 

In our app we have a page, when the data is appended the table view grows

Is there a clean or proper way to do this? 

Thanks!

**Comment by komarovalexander** [comment]
Hi @bay-jacewhitten thanks for that question, I think you can set height 100% 
```
.ka {
  height: 100%;
}
```
https://stackblitz.com/edit/table-many-rows-ts-vdnyydtg

**Comment by bay-jacewhitten** [comment]
@komarovalexander thanks, in that example, if you set the row count to 500, and change the div style height to '100%' you will see at the bottom of the table a huge blank section ( I think its a row with the managed space set to it?)

**Comment by komarovalexander** [comment]
or you can access `ref` of any table element (for example root) and change it any way you want https://stackblitz.com/edit/table-many-rows-ts-f5kshjtf

any solution works for you, which way to go is up to you

hope it helped, thanks for your questions

**Comment by bay-jacewhitten** [comment]
@komarovalexander thank you for your help. I will present these ideas to the team.
