### ISSUE TITLE
Scrolling flickers when using virtual scrolling

### ISSUE THREAD

**Issue by yarokon** [komarovalexander/ka-table#50]
Steps to reproduce:
1. add `virtualScrolling: { }` to the table options
2. populate the table with a small amount of data
3. try to scroll almost to the top or almost to the bottom

type: bug
version: 3.2.1
react: 16.13.1

**Comment by komarovalexander** [comment]
reproduced https://stackblitz.com/edit/table-many-rows-ts-rbc6s8?file=Demo.tsx

**Comment by komarovalexander** [comment]
Thanks for finding this issue!
Fixed in 3.2.2 
example: https://stackblitz.com/edit/table-many-rows-ts-nrsdv7?file=Demo.tsx

**Comment by yarokon** [comment]
Thanks for the quick fix

**Comment by yarokon** [comment]
Hi, @komarovalexander. This issue is reproducible if the row height is different from another row height. Here is a link with a reproducible example: https://codesandbox.io/s/great-almeida-ojwhc?file=/src/Table.js

![ka-table](https://user-images.githubusercontent.com/4423716/107962394-91bd6300-6faf-11eb-9adf-7943a81cb615.gif)

**Comment by komarovalexander** [comment]
Hi @yarokon 
You can use `virtualScrolling.itemHeight` function to specify each row height 
Demo: https://codesandbox.io/s/lucid-herschel-lwmxw?file=/src/Table.js

**Comment by yarokon** [comment]
I have modified the example to be closer to a real-world example: https://codesandbox.io/s/great-almeida-ojwhc?file=/src/Table.js

How should I measure row height in this case? 

It would be more correct if the table did these calculations, like here: [react-windowed-select](https://github.com/jacobworrel/react-windowed-select). Ideally, users using this table shouldn't have to think about how to perform this calculation, because the table has all the data to do this. But if it is not supported, the doc must indicate that additional calculation is required for this case.

**Comment by komarovalexander** [comment]
Thanks for the feedback! 

> Ideally, users using this table shouldn't have to think about how to perform this calculation, because the table has all the data to do this 
The idea of the ka-table to make it a simple, extendable, lightweight, reliable library with a good performance - all these components will be damaged if I add virtualization logic out-of-the-box.  
`react-windowed-select` it is just a wrapper for `react-select` & `react-window` but it is 120kb size (>45% of feature-rich `ka-table`) virtualization here is based on `react-window`  library (868 kB - 3,5 times bigger than the whole ka-table library). 
The more code I add into the library the harder it will be to support, and the more buggy it will be.

I think it is not so common use case, mostly rows have fixed height in virtualized table, but of course, I will add a demo of how to do it using the current API (or will extend it if required), this is the first user request - so it is time to implement it.

I will keep this issue open and will investigate it better coming weeks and let you know if any updates. 
Really appreciate your use cases and all feedback you provided!

**Comment by komarovalexander** [comment]
@yarokon how many dynamic items do you want to render with virtual scrolling >1k, > 10k, 100k, or more?

**Comment by yarokon** [comment]
Please upgrade to version 2.0.4 or higher. At the moment the latest version is 3.0.0

**Comment by komarovalexander** [comment]
Hi @yarokon ,
please update ka-table to `6.7.1` and use code from this demo: https://komarovalexander.github.io/ka-table/#/many-rows-dynamic
