### ISSUE TITLE
How to extract data from the table?

### ISSUE THREAD

**Issue by MishaSavchak** [komarovalexander/ka-table#54]
Is there any method/event to extract data from the table?
For example:
if we use search, filter or something like that then we can't get back filtered data from the table to our component. 
Can you help with that? 

Thanks.

**Comment by komarovalexander** [comment]
Hi
for the quick answer, there is a workaround with prepareTableOptions https://stackblitz.com/edit/table-sorting-ts-rabjrp?file=Demo.tsx (line 39)  
(this is unofficial and I would recommend to use it only as a workaround - probably this will be changed in the further release if the official way will be provided - I will notify you here) 

I will investigate it better and update the issue once Table has a better solution

Thank you for the good question

**Comment by MishaSavchak** [comment]
Hi Alexander,
It super awesome for me. Thanks for the your quick response and for the excellent job.

Thanks!

**Comment by komarovalexander** [comment]
Hi @MishaSavchak 
Started from 3.4.1 you can use kaPropsUtils.getData for this purpose
https://github.com/komarovalexander/ka-table/releases/tag/3.4.1

**Comment by MishaSavchak** [comment]
Hi @komarovalexander,

Cool, it works fine for me :)

Thanks!
