### ISSUE TITLE
Add Server-side Pagination option to Pagination

### ISSUE THREAD

**Issue by BedroomDev** [komarovalexander/ka-table#58]
Would be nice to be possible to add a total number of pages together with the current index.

This way Server-sided pagination is possible, useful and needed for Rest API data.

Usage example : 
https://developer.wordpress.org/rest-api/using-the-rest-api/pagination/

**Comment by komarovalexander** [comment]
Hi. Thanks for great proposal! I will implement it in further releases in June

**Comment by komarovalexander** [comment]
you can use it starting from 3.7.1 version 
https://github.com/komarovalexander/ka-table/releases/tag/3.7.1

**Comment by BedroomDev** [comment]
Thank you very much! I tried to implement it myself and did mostly the same thing, but i could get Typescript to work/compile
