### ISSUE TITLE
How to format a row selectively

### ISSUE THREAD

**Issue by prabodh1194** [komarovalexander/ka-table#59]
Hi,

I have created a table which displays a bunch of numbers in individual rows and last row displays a sum of those numbers. I need to format that row particularly so as to make it bold or add some border. Is there a row level formatting that I can specify?

Thanks.

**Comment by komarovalexander** [comment]
Hi @prabodh1194 
You can do it in css:

  ```
.ka-table .ka-row:last-child {
    font-weight: bold;
    border-color: red;
  }
```

example https://stackblitz.com/edit/table-overview-ts-og5g7j?file=style.scss

**Comment by prabodh1194** [comment]
Thanks for the neat solution. I definitely didn't think of that.
