### ISSUE TITLE
Nested data support

### ISSUE THREAD

**Issue by yarokon** [komarovalexander/ka-table#62]
Is it possible to define a key prop using lodash-like dot paths syntax to reference nested values?

**Comment by komarovalexander** [comment]
HI, check this demo https://stackblitz.com/edit/table-custom-cell-js?file=Demo.js 
as in js, you can set field name with dots
![image](https://user-images.githubusercontent.com/17903747/83891686-dbca2580-a74d-11ea-9f39-a180d92dfcb9.png)
I've decided to avoid this approach 
but I've added fieldParents property where you can set up the same settings but in another way

tell me if it is not sufficient for you

**Comment by komarovalexander** [comment]
@yarokon actually I don't like my solution with fieldParents, so will be released next major 4.0 version at the end of this week where lodash-like dot paths syntax will be used instead of fieldParents

**Comment by komarovalexander** [comment]
starting from version 4.0 fieldParents were removed and lodash-like dot paths syntax is used instead
