### ISSUE TITLE
How to pass additional props for <tr />?

### ISSUE THREAD

**Issue by yarokon** [komarovalexander/ka-table#67]
Recently, I received a requirement to show a `tooltip` for each row that will show a description. But it seems that it's not possible to do it right now. It will be nice to have `rowProps` prop to customize each row of the table. In addition, it would be useful, for example, to change the background color depending on the row data. I know that there is an example showing additional data at the bottom of the table, but it does not feet the client requirements. As a workaround, I can wrap each cell and define a tooltip, but it would be better to avoid this solution.

Is it possible to implement it with an existing API? If not, it would be great to have this:
`rowProps={({ rowData }) => ({ title: rowData.description })}`

![Selection_545](https://user-images.githubusercontent.com/4423716/87781360-379dc900-c839-11ea-880d-bb85b9834ef7.png)

**Comment by komarovalexander** [comment]
Hi, @yarokon  I'm working on this now, at the end of this week Table will have such functionality. Thanks for the proposed scenario I will add something similar to the demos page

**Comment by komarovalexander** [comment]
Hi @yarokon
Starting from new major release 4.0.1 this ability has been added. 
See demo https://komarovalexander.github.io/ka-table/#/custom-attributes

be aware that some breaking changes were made in new major version 
info how to fix them are available here https://github.com/komarovalexander/ka-table/releases/tag/4.0.1
