### ISSUE TITLE
Implementation of mutiselect range of elements in table

### ISSUE THREAD

**Issue by boverU** [komarovalexander/ka-table#73]
Can you make the ability to multiselect range of elements? For example I have 100 elements, I wanna select from 5th to 60th element. Expected behavior - clicking the element I want to start select, then pressing **shift** and the which to I wanted to select. Kind of slice method.

**Comment by komarovalexander** [comment]
selectRowsRange action creator was added for this purpose, see https://komarovalexander.github.io/ka-table/#/selection demo

thanks for the useful issue!
