### ISSUE TITLE
Warning when adding pagination info to tablePropsInit

### ISSUE THREAD

**Issue by boverU** [komarovalexander/ka-table#78]
when adding this piece of code` paging: {
      enabled: true,
      pageIndex: 1,
      pageSize: 10,
    },` from demo,  run into the following error - **Cannot update a component (`KaTable`) while rendering a different component (`PagingPages`). To locate the bad setState() call inside `PagingPages`, follow the stack trace as described in https://fb.me/setstate-in-render**. 
Passing the total number of elements like so 
`useEffect(() => {
    dispatch(updatePagesCount(props.total));
  }, [props.total]);`

**Comment by komarovalexander** [comment]
Fixed in 4.3.2
Thanks for finding that!
