### ISSUE TITLE
Order by Selected Rows

### ISSUE THREAD

**Issue by danilodecanini** [komarovalexander/ka-table#86]
Hey there,

I would like to know how I can insert a filter in SelectionHeader to order by selected rows and deselected rows, a ordernation just like the other fields with the arrow down and arrow up, is there an easy way to do so?

**Comment by komarovalexander** [comment]
Hi at this time there is no out-of-the-box solution for that 
but I can propose you a workaround please check the demo and comments in it
https://stackblitz.com/edit/table-selection-ts-j1crry?file=Demo.tsx

**Comment by danilodecanini** [comment]
Hi @komarovalexander, I checked the demo and replicate to my code and works pretty well! 

Thank you so much
