### ISSUE TITLE
Selecting items according to their filter

### ISSUE THREAD

**Issue by danilodecanini** [komarovalexander/ka-table#88]
Hey @komarovalexander ,

It's just a question, but is there a way that I can filter my rows and click on 'Select All' checkbox and select just the items that is on the table in that moment?

Idk if i'm clear enough, here's an example:

I have a table with 2 column's: Restaurant Name and City, in that table I filter by city typing a city name that I have a lot of restaurants (5-9 pages) and I want to click on 'Select All' checkbox to select that specific 5-9 pages of restaurants.

**Comment by komarovalexander** [comment]
Hi @danilodecanini I got your requirements,
I think this should be implemented out-of-the-box,
So this weekend this feature will be added in the new version of the component

thanks for this question

**Comment by komarovalexander** [comment]
btw if you need the solution now, you can do it this way with a little bit additional code: https://stackblitz.com/edit/table-selection-ts-eik9cd?file=Demo.tsx

**Comment by komarovalexander** [comment]
Lets keep this issue oppened. I will add some settings to make selection stuff with less code

**Comment by danilodecanini** [comment]
@komarovalexander, thank you again,

I did the way that you did on demos, and it worked perfectly.

The Deselect All works the same way ?

**Comment by komarovalexander** [comment]
If you want to override deselect behavior you also can do it in custom reducer. Let me know if you need help with it

**Comment by komarovalexander** [comment]
to deselect visible items: https://stackblitz.com/edit/table-selection-ts-vgkr2s?file=Demo.tsx
to deselect all filtered items: https://stackblitz.com/edit/table-selection-ts-fef61o?file=Demo.tsx

**Comment by komarovalexander** [comment]
but your question is quite reasonable and maybe it is worth adding a couple of methods to simplify select/deselect for these cases. I will keep this issue opened, will try to find a way how to do it with less code. At least this select/deselect logic seems should be out of the box in kaReducer at least

**Comment by danilodecanini** [comment]
@komarovalexander awesome!

It worked perfectly well!

It would be interesting if in a possible next version the select all and deselect all methods could be more easily to implement!

Thank you again

**Comment by komarovalexander** [comment]
Hi @danilodecanini you can use version 5.2.0 
it has these action creators:
```
 deselectAllFilteredRows()
 selectAllFilteredRows()
```
also there is `kaPropsUtils.areAllFilteredRowsSelected(tableProps)` for checkbox in the header

release: https://github.com/komarovalexander/ka-table/releases/tag/5.2.0
demo: https://komarovalexander.github.io/ka-table/#/selection

**Comment by danilodecanini** [comment]
Hey @komarovalexander,

I'll use this new version with the new actions, thank you again and congrats for this awesome library.

**Comment by fshahmt** [comment]
Hey @komarovalexander, back again with another question. 

So, the deal is that when I am using the table it's all good but I get a few issues here and there. The most recent one being when I use the deselectAllFilteredRows, it just lags and sometimes just breaks the page. I tried with the demo too and as soon as I set Array(10000), it starts lagging. Is there a workaround because I work with a lot of data (often times over 10000) https://stackblitz.com/edit/table-selection-ts?file=Demo.tsx

Please do let me know
