### ISSUE TITLE
Table does not show data with dots in the property name 

### ISSUE THREAD

**Issue by Procenkin** [komarovalexander/ka-table#91]
If there is '.' in the field name then property data will not be shown

TableProps = {
  columns: [
    { **key: 'column1.one'**, title: 'Column 1', dataType: DataType.String },
    { **key: 'column2.two'**, title: 'Column 2', dataType: DataType.String },
    { **key: 'column3.three'**, title: 'Column 3', dataType: DataType.String },
  ],
  data: [
{**key:"column1.one"**, title:"Column 1", dataType:"string"},
{**key:"column2.two"**, title:"Column 2", dataType:"string"},
{**key:"column3.three"**, title:"Column 3", dataType:"string"},
],
  rowKeyField: 'id',
  sortingMode: SortingMode.Single,
};

**Comment by komarovalexander** [comment]
Hi @Procenkin ,
starting from 5.3.0 you can override the default delimiter by this way:
```
import defaultOptions from 'ka-table/defaultOptions';
defaultOptions.fieldDelimiter = '';
```
Demo https://stackblitz.com/edit/table-overview-js-xfrh64?file=Demo.js

cheers
